(()=>{
const SUPA='https://fhilbjbuhtqdwvxhiedz.supabase.co';
const KEY='sb_publishable_sXoO_u65OB-SPt9OFPiz5A_XMUIIprl';
const BASE=SUPA+'/rest/v1/yamim_noraim_registrations';
const SEATING=SUPA+'/rest/v1/yamim_noraim_seating';
const H={'apikey':KEY,'Content-Type':'application/json'};
const db=supabase.createClient(SUPA,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);let registrations=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const sum=k=>registrations.reduce((a,r)=>a+(Number(r[k])||0),0);
async function loadRegs(){const status=$('statusEl'),rows=$('rowsEl');status.textContent='טוען...';try{const r=await fetch(BASE+'?select=id,family_name,family_name_normalized,rh_men,rh_women,yk_men,yk_women,notes,updated_at&order=family_name.asc',{headers:H});const t=await r.text();if(!r.ok)throw Error('HTTP '+r.status+' — '+t);registrations=JSON.parse(t);renderRegs()}catch(e){status.textContent='שגיאה בטעינת הנתונים: '+e.message;rows.innerHTML=''}}
function renderRegs(){$('rhMenEl').textContent=sum('rh_men');$('rhWomenEl').textContent=sum('rh_women');$('ykMenEl').textContent=sum('yk_men');$('ykWomenEl').textContent=sum('yk_women');$('statusEl').textContent=registrations.length+' משפחות';$('rowsEl').innerHTML=registrations.map((r,i)=>`<tr id="row-${i}"><td><input value="${esc(r.family_name)}" data-f="family_name"></td><td><input type="number" min="0" max="6" value="${r.rh_men}" data-f="rh_men"></td><td><input type="number" min="0" max="6" value="${r.rh_women}" data-f="rh_women"></td><td><input type="number" min="0" max="6" value="${r.yk_men}" data-f="yk_men"></td><td><input type="number" min="0" max="6" value="${r.yk_women}" data-f="yk_women"></td><td><textarea data-f="notes">${esc(r.notes||'')}</textarea></td><td data-sort-date="${r.updated_at?Date.parse(r.updated_at)||0:0}">${r.updated_at?new Date(r.updated_at).toLocaleString('he-IL'):''}</td><td><div class="actions"><button class="btn" onclick="YNAdmin.saveRow(${i})">שמור</button><button class="btn danger" onclick="YNAdmin.deleteRow(${i})">מחק</button></div></td></tr>`).join('')}
async function saveRow(i){const r=registrations[i],tr=$('row-'+i),v={};tr.querySelectorAll('[data-f]').forEach(el=>v[el.dataset.f]=el.type==='number'?Number(el.value):el.value.trim());if(!v.family_name||['rh_men','rh_women','yk_men','yk_women'].some(k=>!Number.isInteger(v[k])||v[k]<0||v[k]>6)){tr.className='error';$('statusEl').textContent='ערכים לא תקינים בשורה';return}v.family_name_normalized=v.family_name.replace(/\s+/g,' ').toLocaleLowerCase('he-IL');try{const res=await fetch(BASE+'?id=eq.'+encodeURIComponent(r.id),{method:'PATCH',headers:{...H,'Prefer':'return=minimal'},body:JSON.stringify(v)});if(!res.ok)throw Error(await res.text());tr.className='saved';$('statusEl').textContent='נשמר בהצלחה';setTimeout(loadRegs,500)}catch(e){tr.className='error';$('statusEl').textContent='שגיאה בשמירה: '+e.message}}
async function deleteRow(i){const r=registrations[i];if(!confirm(`למחוק את משפחת ${r.family_name}?\n\nהפעולה תמחק גם את כל שיבוצי המושבים של המשפחה ולא ניתן לבטל אותה.`))return;$('statusEl').textContent='מוחק...';try{let res=await fetch(SEATING+'?family_name=eq.'+encodeURIComponent(r.family_name),{method:'DELETE',headers:H});if(!res.ok)throw Error('שגיאה במחיקת השיבוצים');res=await fetch(BASE+'?id=eq.'+encodeURIComponent(r.id),{method:'DELETE',headers:H});if(!res.ok)throw Error('שגיאה במחיקת הרשומה');await loadRegs()}catch(e){$('statusEl').textContent='שגיאה במחיקה: '+e.message}}
function exportCsv(){const cell=v=>{const s=String(v??'');return /[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s};const head=['משפחה','ראש השנה גברים','ראש השנה נשים','יום כיפור גברים','יום כיפור נשים','הערות','עודכן'];const lines=[head,...registrations.map(r=>[r.family_name,r.rh_men,r.rh_women,r.yk_men,r.yk_women,r.notes||'',r.updated_at||''])].map(row=>row.map(cell).join(','));const blob=new Blob(['\ufeff'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='yamim-noraim-registrations.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
async function authState(){const {data:{session}}=await db.auth.getSession();const note=$('adminAuth'),login=$('adminLogin'),add=$('adminAdd'),list=$('adminsList');if(!session?.user){note.textContent='כדי לנהל מנהלים יש להתחבר עם חשבון Google של מנהל.';login.classList.remove('hidden');add.classList.add('hidden');list.innerHTML='';return}login.classList.add('hidden');note.textContent='מחובר: '+(session.user.email||'');await loadAdmins(session.user.email||'')}
async function loadAdmins(current){const add=$('adminAdd'),list=$('adminsList');const {data,error}=await db.from('yamim_noraim_admins').select('email,created_at').order('email');if(error){add.classList.add('hidden');list.innerHTML='<div class="authNote">אין הרשאה לנהל מנהלים.</div>';return}if(!data?.length){add.classList.add('hidden');list.innerHTML='<div class="authNote">החשבון המחובר אינו מוגדר כמנהל.</div>';return}add.classList.remove('hidden');list.innerHTML=data.map(a=>`<div class="adminRow"><div><div class="adminEmail">${esc(a.email)}</div>${a.email.toLowerCase()===String(current).toLowerCase()?'<div class="authNote">זה החשבון שלך</div>':''}</div><button class="btn danger" data-email="${esc(a.email)}">הסר</button></div>`).join('');list.querySelectorAll('[data-email]').forEach(b=>b.onclick=()=>removeAdmin(b.dataset.email,current))}
async function addAdmin(){const el=$('adminEmail'),email=el.value.trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){alert('יש להזין כתובת אימייל תקינה.');return}const {error}=await db.from('yamim_noraim_admins').insert({email});if(error){alert(error.code==='23505'?'הכתובת כבר מוגדרת כמנהל.':'לא ניתן להוסיף מנהל: '+error.message);return}el.value='';await authState()}
async function removeAdmin(email,current){const self=email.toLowerCase()===String(current).toLowerCase();if(!confirm(self?`להסיר את ${email} מרשימת המנהלים?\nזה החשבון שבו אתה מחובר כרגע.`:`להסיר את ${email} מרשימת המנהלים?`))return;const {error}=await db.from('yamim_noraim_admins').delete().eq('email',email);if(error){alert('לא ניתן להסיר מנהל: '+error.message);return}await authState()}
$('refreshBtn').onclick=loadRegs;$('exportBtn').onclick=exportCsv;$('adminLogin').onclick=()=>db.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname}});$('addAdminBtn').onclick=addAdmin;$('adminEmail').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addAdmin()}});db.auth.onAuthStateChange(()=>setTimeout(authState,0));window.YNAdmin={saveRow,deleteRow};loadRegs();authState();
})();
