(()=>{
const SUPA='https://fhilbjbuhtqdwvxhiedz.supabase.co';
const KEY='sb_publishable_sXoO_u65OB-SPt9OFPiz5A_XMUIIprl';
const SITE='https://eyal108.github.io/yamin-noraim2026/';
const TENANT_TABLES=new Set(['yamim_noraim_request_lists','yamim_noraim_layouts','yamim_noraim_families','yamim_noraim_requests','yamim_noraim_seating_v2','yamim_noraim_automatic_proposals','yamim_noraim_synagogue_admins']);
const ZERO='00000000-0000-0000-0000-000000000000';
let access=null,baseClient=null,wrappedClient=null;
function rawClient(){if(!baseClient)baseClient=supabase.createClient(SUPA,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return baseClient}
function tenantId(){return localStorage.getItem('yn:synagogue')||''}
function addTenant(rows,id){if(Array.isArray(rows))return rows.map(x=>({...x,synagogue_id:id}));return {...(rows||{}),synagogue_id:id}}
function wrappedRelation(rel,table){if(!TENANT_TABLES.has(table))return rel;return new Proxy(rel,{get(target,prop){if(prop==='select')return(...args)=>target.select(...args).eq('synagogue_id',tenantId()||ZERO);if(prop==='insert')return(rows,...rest)=>{const id=tenantId();if(!id)throw Error('לא נבחר בית כנסת');return target.insert(addTenant(rows,id),...rest)};if(prop==='upsert')return(rows,...rest)=>{const id=tenantId();if(!id)throw Error('לא נבחר בית כנסת');return target.upsert(addTenant(rows,id),...rest)};if(prop==='update')return(values,...rest)=>target.update(values,...rest).eq('synagogue_id',tenantId()||ZERO);if(prop==='delete')return(...args)=>target.delete(...args).eq('synagogue_id',tenantId()||ZERO);const v=target[prop];return typeof v==='function'?v.bind(target):v}})}
function makeClient(){if(wrappedClient)return wrappedClient;const c=rawClient();wrappedClient=new Proxy(c,{get(target,prop){if(prop==='from')return table=>{const mapped=table==='yamim_noraim_admins'?'yamim_noraim_synagogue_admins':table;return wrappedRelation(target.from(mapped),mapped)};const v=target[prop];return typeof v==='function'?v.bind(target):v}});return wrappedClient}
const norm=s=>String(s??'').trim().replace(/\s+/g,' ').toLocaleLowerCase('he-IL');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function loadAccess(db,session){if(!session?.user?.email){access={isAdmin:false,isProductAdmin:false,synagogues:[],synagogueId:null};return access}const raw=rawClient(),email=(session.user.email||'').toLowerCase();const [sr,pr]=await Promise.all([raw.from('yamim_noraim_synagogues').select('id,slug,name,is_active,ai_enabled').order('name'),raw.from('yamim_noraim_product_admins').select('email').eq('email',email).maybeSingle()]);const isProductAdmin=!pr.error&&!!pr.data,all=sr.error?[]:(sr.data||[]),synagogues=isProductAdmin?all:all.filter(s=>s.is_active);const u=new URL(location.href),org=u.searchParams.get('org');let chosen=synagogues.find(s=>s.slug===org||s.id===org)?.id||localStorage.getItem('yn:synagogue');if(!synagogues.some(s=>s.id===chosen))chosen=synagogues[0]?.id||null;if(chosen)localStorage.setItem('yn:synagogue',chosen);else localStorage.removeItem('yn:synagogue');access={isAdmin:isProductAdmin||synagogues.length>0,isProductAdmin,synagogues,synagogueId:chosen,current:synagogues.find(s=>s.id===chosen)||null};window.YNAccess=access;mountTenantSelector();applyAiGate();return access}
function mountTenantSelector(){if(!access?.isAdmin)return;const nav=document.querySelector('.appTabs');if(!nav||document.getElementById('ynTenantBar'))return;const bar=document.createElement('div');bar.id='ynTenantBar';bar.style.cssText='display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin:10px 0 16px;padding:10px 12px;background:#eef2ef;border-radius:12px';bar.innerHTML=`<b>בית כנסת:</b><select id="ynTenantSelect" style="min-width:180px;padding:7px;border:1px solid #c9d1cc;border-radius:8px">${access.synagogues.map(s=>`<option value="${s.id}"${s.id===access.synagogueId?' selected':''}>${esc(s.name)}${s.is_active?'':' — לא פעיל'}</option>`).join('')}</select>${access.isProductAdmin?'<a class="btn" href="product-admin.html">ניהול מוצר</a>':''}`;nav.insertAdjacentElement('afterend',bar);const sel=bar.querySelector('select');sel.onchange=e=>{const id=e.target.value,s=access.synagogues.find(x=>x.id===id);localStorage.setItem('yn:synagogue',id);const u=new URL(location.href);if(s)u.searchParams.set('org',s.slug);location.href=u.toString()};if(access.synagogues.length===1&&!access.isProductAdmin)sel.disabled=true;const cur=access.current;if(cur){document.querySelectorAll('a[href="index.html"]').forEach(a=>a.href='index.html?org='+encodeURIComponent(cur.slug))}}
function applyAiGate(){const cb=document.getElementById('useAiCheck');if(!cb||!access?.current)return;const enabled=!!access.current.ai_enabled;cb.checked=enabled&&cb.checked;cb.disabled=!enabled;const label=cb.closest('.engineOption');if(label){let note=label.querySelector('.aiTenantNote');if(!enabled){if(!note){note=document.createElement('small');note.className='aiTenantNote';note.style.cssText='display:block;color:#8a3b32;margin-top:4px';label.appendChild(note)}note.textContent='AI אינו מופעל לבית הכנסת הזה. רק מנהל המוצר יכול להפעיל אותו.'}else note?.remove()}}
async function isAdmin(db,session){const a=await loadAccess(db,session);return a.isAdmin}
function uid(prefix='id'){return prefix+'-'+(crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2))}
window.YNGeneric={SUPA,KEY,SITE,makeClient,makeRawClient:rawClient,norm,esc,isAdmin,loadAccess,getAccess:()=>access,tenantId,uid};
})();
