(()=>{
const {SITE,makeRawClient,esc}=YNGeneric,db=makeRawClient(),$=id=>document.getElementById(id);let session=null,synagogues=[],selected=null;
function status(t){$('status').textContent=t||''}
function cur(){return synagogues.find(x=>x.id===selected)||null}
async function gate(){const r=await db.auth.getSession();session=r.data.session;if(!session?.user){$('loginGate').innerHTML='יש להתחבר כמנהל מוצר. <button id="loginBtn" class="btn primary">התחבר עם Google</button>';$('loginBtn').onclick=()=>db.auth.signInWithOAuth({provider:'google',options:{redirectTo:SITE+'product-admin.html'}});return false}const pr=await db.from('yamim_noraim_product_admins').select('email').eq('email',(session.user.email||'').toLowerCase()).maybeSingle();if(pr.error||!pr.data){$('loginGate').textContent='לחשבון המחובר אין הרשאת מנהל מוצר.';return false}$('loginGate').classList.add('hidden');$('productApp').classList.remove('hidden');return true}
async function load(prefer=null){status('טוען...');const {data,error}=await db.from('yamim_noraim_synagogues').select('id,slug,name,is_active,ai_enabled,created_at,updated_at').order('created_at');if(error)throw error;synagogues=data||[];selected=prefer||selected||localStorage.getItem('yn:synagogue')||synagogues[0]?.id||null;if(!synagogues.some(x=>x.id===selected))selected=synagogues[0]?.id||null;renderList();await renderDetail();status('')}
function renderList(){$('synList').innerHTML=synagogues.length?synagogues.map(s=>`<div class="synRow ${s.id===selected?'active':''} ${s.is_active?'':'inactive'}" data-id="${s.id}"><div><b>${esc(s.name)}</b><div class="muted">${esc(s.slug)}</div></div><div>${s.ai_enabled?'<span class="badge on">AI</span>':'<span class="badge off">AI כבוי</span>'}</div></div>`).join(''):'<div class="empty">עדיין לא נוצרו בתי כנסת.</div>';$('synList').querySelectorAll('[data-id]').forEach(x=>x.onclick=async()=>{selected=x.dataset.id;localStorage.setItem('yn:synagogue',selected);renderList();await renderDetail()})}
async function renderDetail(){const s=cur();$('detailEmpty').classList.toggle('hidden',!!s);$('detail').classList.toggle('hidden',!s);if(!s)return;$('synName').textContent=s.name;$('activeBadge').textContent=s.is_active?'פעיל':'לא פעיל';$('activeBadge').className='badge '+(s.is_active?'on':'off');$('aiBadge').textContent=s.ai_enabled?'AI פעיל':'AI כבוי';$('aiBadge').className='badge '+(s.ai_enabled?'on':'off');$('activeBtn').textContent=s.is_active?'השבת בית כנסת':'הפעל בית כנסת';$('aiBtn').textContent=s.ai_enabled?'כבה AI':'הפעל AI';const link=SITE+'?org='+encodeURIComponent(s.slug);$('publicLink').textContent=link;$('openAdminBtn').onclick=()=>{localStorage.setItem('yn:synagogue',s.id);location.href='admin.html?org='+encodeURIComponent(s.slug)};await loadManagers()}
async function loadManagers(){const s=cur();if(!s)return;const {data,error}=await db.from('yamim_noraim_synagogue_admins').select('email,created_at').eq('synagogue_id',s.id).order('email');if(error){$('managerList').innerHTML='<div class="empty">לא ניתן לטעון מנהלים.</div>';return}$('managerList').innerHTML=(data||[]).length?(data||[]).map(a=>`<div class="managerRow"><span>${esc(a.email)}</span><button class="btn danger" data-email="${esc(a.email)}">הסר</button></div>`).join(''):'<div class="empty">אין מנהלים לבית הכנסת הזה.</div>';$('managerList').querySelectorAll('[data-email]').forEach(b=>b.onclick=()=>removeManager(b.dataset.email))}
async function newSyn(){const name=prompt('שם בית הכנסת:');if(!name?.trim())return;const slug='syn-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6);const {data,error}=await db.from('yamim_noraim_synagogues').insert({name:name.trim(),slug,is_active:true,ai_enabled:false}).select('id').single();if(error)return alert('לא ניתן ליצור בית כנסת: '+error.message);await load(data.id)}
async function rename(){const s=cur();if(!s)return;const name=prompt('שם חדש לבית הכנסת:',s.name);if(!name?.trim()||name.trim()===s.name)return;const {error}=await db.from('yamim_noraim_synagogues').update({name:name.trim(),updated_at:new Date().toISOString()}).eq('id',s.id);if(error)return alert(error.message);await load(s.id)}
async function toggle(field){const s=cur();if(!s)return;if(field==='ai_enabled'&&!s.ai_enabled&&!confirm('להפעיל AI לבית הכנסת הזה? שימוש ב-AI יחויב בחשבון ה-OpenAI של המוצר.'))return;const {error}=await db.from('yamim_noraim_synagogues').update({[field]:!s[field],updated_at:new Date().toISOString()}).eq('id',s.id);if(error)return alert(error.message);await load(s.id)}
async function addManager(){const s=cur(),input=$('managerEmail'),email=input.value.trim().toLowerCase();if(!s||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return alert('יש להזין כתובת אימייל תקינה.');const {error}=await db.from('yamim_noraim_synagogue_admins').insert({synagogue_id:s.id,email});if(error)return alert(error.code==='23505'?'הכתובת כבר מוגדרת כמנהל.':'לא ניתן להוסיף מנהל: '+error.message);input.value='';await loadManagers()}
async function removeManager(email){const s=cur();if(!s||!confirm('להסיר את '+email+' מניהול בית הכנסת?'))return;const {error}=await db.from('yamim_noraim_synagogue_admins').delete().eq('synagogue_id',s.id).eq('email',email);if(error)return alert(error.message);await loadManagers()}
$('newSynBtn').onclick=newSyn;$('refreshBtn').onclick=()=>load(selected);$('logoutBtn').onclick=async()=>{await db.auth.signOut();location.reload()};$('renameBtn').onclick=rename;$('activeBtn').onclick=()=>toggle('is_active');$('aiBtn').onclick=()=>toggle('ai_enabled');$('addManagerBtn').onclick=addManager;$('managerEmail').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addManager()}});$('copyLinkBtn').onclick=async()=>{const s=cur();if(!s)return;try{await navigator.clipboard.writeText(SITE+'?org='+s.slug);status('הקישור הועתק')}catch{status('לא ניתן להעתיק אוטומטית. אפשר לסמן את הקישור ולהעתיק.')}};
(async()=>{if(await gate())try{await load()}catch(e){status('שגיאה: '+e.message)}})();
})();
