(()=>{
const {SUPA,KEY,SITE,makeClient,isAdmin}=YNGeneric,db=makeClient(),$=id=>document.getElementById(id);
const BASE=SUPA+'/functions/v1/request-form',org=new URL(location.href).searchParams.get('org')||'';
const FN=BASE+(org?'?org='+encodeURIComponent(org):'');
let lists=[],plans=new Map(),frags=new Map(),timer=null,lastLookup='',lookupSeq=0,lookupController=null,authSeq=0,authTimer=null;
let currentListId=null,activePriority=1,selectedGroup=null,touchSelection=null;
function endpoint(extra=''){const sep=FN.includes('?')?'&':'?';return extra?FN+sep+extra:FN}
function val(id){const n=Number($(id)?.value);return Number.isInteger(n)&&n>=0&&n<=100?n:null}
function msg(t,e=false){const x=$('msg');x.textContent=t||'';x.className='msg '+(t?(e?'err':'ok'):'')}
function listById(id){return lists.find(l=>String(l.id)===String(id))||null}
function uid(p='g'){return p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8)}
function esc(s){return YNGeneric.esc(String(s??''))}
function clone(v){return typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v))}
function emptyPlan(){return{1:[],2:[],3:[]}}
function getPlan(listId){const k=String(listId);if(!plans.has(k))plans.set(k,emptyPlan());return plans.get(k)}
function assignments(listId,priority=activePriority){return getPlan(listId)[priority]||[]}
function setAssignments(listId,priority,a){getPlan(listId)[priority]=a}
function countFor(listId,sec){return val(`${sec}-${listId}`)||0}
function requestedTotal(listId){return countFor(listId,'men')+countFor(listId,'women')}
function assignedCount(listId,priority,sec){return assignments(listId,priority).filter(a=>a.section===sec).length}
function priorityUsed(listId,p){return assignments(listId,p).length>0}
function priorityComplete(listId,p){return assignedCount(listId,p,'men')===countFor(listId,'men')&&assignedCount(listId,p,'women')===countFor(listId,'women')}
function fragKey(listId,p,sec){return `${listId}|${p}|${sec}`}
function getFrags(listId,p,sec){const rem=Math.max(0,countFor(listId,sec)-assignedCount(listId,p,sec)),k=fragKey(listId,p,sec),a=frags.get(k);if(rem<=0)return[];if(Array.isArray(a)&&a.every(n=>Number.isInteger(n)&&n>0)&&a.reduce((x,y)=>x+y,0)===rem)return a;const out=[rem];frags.set(k,out);return out}
function setFrags(listId,p,sec,a){frags.set(fragKey(listId,p,sec),a)}
function resetFragsForList(listId){for(const k of [...frags.keys()])if(k.startsWith(String(listId)+'|'))frags.delete(k)}
function seatLabel(list,seatId){const s=list?.layout?YNLayout.buildSeats(list.layout).find(x=>x.id===seatId):null;if(!s)return seatId;return `${s.area_name||''} · שורה ${s.row_label||s.row} · מקום ${s.col||s.seat_index}`.replace(/^ · /,'')}
function priorityName(p){return `עדיפות ${p}`}
function applySynagogue(data){if(data?.synagogue?.name){document.title='רישום למקומות — '+data.synagogue.name;const h=document.querySelector('h1');if(h)h.textContent='רישום למקומות — '+data.synagogue.name}}
async function call(url,opts={}){const r=await fetch(url,{...opts,headers:{'Content-Type':'application/json','apikey':KEY,...(opts.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||('HTTP '+r.status));return data}
function renderPrefSummary(listId){const l=listById(listId),box=document.querySelector(`[data-pref-summary="${String(listId)}"]`);if(!box||!l)return;const total=requestedTotal(listId),parts=[];for(let p=1;p<=3;p++){const n=assignments(listId,p).length,used=n>0,complete=total>0&&priorityComplete(listId,p);parts.push(`<span class="prefSummaryItem priority${p}${complete?' complete':''}${used&&!complete?' incomplete':''}"><b>${priorityName(p)}</b><span>${used?`${n}/${total} מקומות${complete?' · הושלמה':' · לא הושלמה'}`:'לא נבחרה'}</span></span>`)}box.innerHTML=parts.join('')}
function renderLists(){const box=$('requestCards');if(!lists.length){box.innerHTML='<div class="closed">כרגע אין רשימות פתוחות לרישום.</div>';$('save').disabled=true;return}box.innerHTML=lists.map(l=>`<div class="card requestCard" data-list="${l.id}"><h2>${esc(l.title)}</h2><div class="requestGrid"><div class="countField"><label for="men-${l.id}">גברים</label><input id="men-${l.id}" type="number" min="0" max="100" step="1" value="0" inputmode="numeric"></div><div class="countField"><label for="women-${l.id}">נשים</label><input id="women-${l.id}" type="number" min="0" max="100" step="1" value="0" inputmode="numeric"></div></div><div class="seatPreferenceBox"><div class="seatPreferenceHead"><b>מקומות מועדפים</b><span>אפשר להכין עד 3 חלופות מלאות. כל חלופה כוללת את כל מספר המקומות שביקשתם.</span></div>${l.layout?`<button class="prefOpen" type="button" data-pref-open="${l.id}">בחירת מקומות על התרשים</button><div class="prefSummary" data-pref-summary="${l.id}"></div>`:`<div class="prefUnavailable">לא הוגדרה תצורת ברירת־מחדל לרשימה זו, ולכן אין כרגע אפשרות לבחור מקום ספציפי.</div>`}</div></div>`).join('');box.querySelectorAll('[data-pref-open]').forEach(b=>b.onclick=()=>openPrefDialog(b.dataset.prefOpen));for(const l of lists){['men','women'].forEach(sec=>{const x=$(`${sec}-${l.id}`);if(x)x.addEventListener('input',()=>{resetFragsForList(l.id);renderPrefSummary(l.id);if(currentListId===String(l.id)&&$('seatPrefDialog')?.open)renderEditor()})});renderPrefSummary(l.id)}$('save').disabled=false}
async function loadLists(){try{const data=await call(FN);applySynagogue(data);lists=data.lists||[];plans.clear();frags.clear();renderLists()}catch(e){$('requestCards').innerHTML='<div class="closed">לא ניתן לטעון את רשימות הרישום כרגע.</div>';msg(e.message==='Synagogue not found'?'הקישור לבית הכנסת אינו תקין.':'שגיאה בטעינת הנתונים.',true)}}
function clearValues(){plans.clear();frags.clear();for(const l of lists){const m=$('men-'+l.id),w=$('women-'+l.id);if(m)m.value=0;if(w)w.value=0;renderPrefSummary(l.id)}$('notes').value='';$('existing').classList.remove('show')}
function normalizeLoadedPlans(data){const grouped=new Map();for(const p of data.seat_preferences||[]){const lid=String(p.request_list_id),priority=Number(p.priority),plan=grouped.get(lid)||emptyPlan();if(priority>=1&&priority<=3)plan[priority].push({seat_id:String(p.seat_id),section:p.section==='women'?'women':'men',seat_group:p.seat_group?String(p.seat_group):`legacy-${priority}-${String(p.seat_id)}`});grouped.set(lid,plan)}return grouped}
async function lookup(){clearTimeout(timer);timer=null;const name=$('family').value.trim().replace(/\s+/g,' ');if(!name){lastLookup='';lookupController?.abort();lookupSeq++;clearValues();msg('');return}if(name===lastLookup)return;const seq=++lookupSeq;lookupController?.abort();const controller=new AbortController();lookupController=controller;try{const data=await call(endpoint('family='+encodeURIComponent(name)),{signal:controller.signal});if(seq!==lookupSeq)return;applySynagogue(data);if(Array.isArray(data.lists)){const old=lists.map(x=>`${x.id}:${x.default_layout_id||''}`).join(','),next=data.lists.map(x=>`${x.id}:${x.default_layout_id||''}`).join(',');if(old!==next){lists=data.lists;renderLists()}}clearValues();if(data.family){$('family').value=data.family.family_name;$('notes').value=data.family.notes||'';$('existing').classList.add('show');const map=new Map((data.entries||[]).map(e=>[String(e.request_list_id),e]));for(const l of lists){const e=map.get(String(l.id));if(e){$('men-'+l.id).value=e.men;$('women-'+l.id).value=e.women}}plans=normalizeLoadedPlans(data);for(const l of lists)renderPrefSummary(l.id)}lastLookup=name;msg('')}catch(e){if(e?.name==='AbortError'||seq!==lookupSeq)return;lastLookup='';msg('לא הצלחנו לבדוק רישום קיים.',true)}finally{if(lookupController===controller)lookupController=null}}
function ensurePrefDialog(){if($('seatPrefDialog'))return;const d=document.createElement('dialog');d.id='seatPrefDialog';d.className='seatPrefDialog';d.innerHTML=`<div class="prefDialogHead"><div><h2 id="seatPrefTitle"></h2><div class="prefDialogNote">כל עדיפות היא חלופת שיבוץ מלאה. גררו את הקבוצות אל התרשים; אפשר לפצל, להעביר ולשחרר כמו במסך סידור המושבים.</div></div><button id="seatPrefCloseX" type="button" class="prefCloseX" aria-label="סגירה">×</button></div><div class="priorityTabs" id="priorityTabs"><button type="button" data-priority="1" class="priorityTab priority1">עדיפות 1</button><button type="button" data-priority="2" class="priorityTab priority2">עדיפות 2</button><button type="button" data-priority="3" class="priorityTab priority3">עדיפות 3</button></div><div class="preferenceWorkspace"><aside class="prefRequests prefWomenReq"><h3>בקשות נשים</h3><div class="prefHelp">גררו קבוצה או לחצו עליה ואז על כיסא יעד.</div><div id="prefWomenRequests"></div></aside><section class="prefHall"><div class="front"><div id="prefFrontLeft"></div><div id="prefFrontCenter" class="ark"></div><div id="prefFrontRight"></div></div><div id="prefLayoutMap" class="layoutMap"></div><div id="prefGroupTools" class="tools"><b id="prefGroupTitle"></b><div class="actions"><span>פצל לקבוצה ראשונה של</span><select id="prefSplitCount"></select><button id="prefSplitGroup" type="button" class="btn">פצל</button><button id="prefReleaseGroup" type="button" class="btn">שחרר קבוצה</button><button id="prefCloseTools" type="button" class="btn">סגור</button></div></div><div id="prefEditorStatus" class="status"></div></section><aside class="prefRequests prefMenReq"><h3>בקשות גברים</h3><div class="prefHelp">גררו קבוצה או לחצו עליה ואז על כיסא יעד.</div><div id="prefMenRequests"></div></aside></div><div class="prefEditorFooter"><div id="prefPriorityProgress"></div><div class="prefDialogActions"><button id="seatPrefClearPriority" type="button">נקה עדיפות זו</button><button id="seatPrefDone" type="button" class="primary">סיום</button></div></div>`;document.body.appendChild(d);const sd=document.createElement('dialog');sd.id='prefSplitDialog';sd.className='prefSplitDialog';sd.innerHTML='<h3 id="prefSplitText">פיצול קבוצה</h3><div id="prefSplitChoices" class="splitChoices"></div><button id="prefCloseSplit" type="button">סגור</button>';document.body.appendChild(sd);$('seatPrefCloseX').onclick=()=>d.close();$('seatPrefDone').onclick=()=>d.close();$('seatPrefClearPriority').onclick=()=>clearPriority();$('prefCloseTools').onclick=()=>{selectedGroup=null;$('prefGroupTools').classList.remove('show');renderEditor()};$('prefReleaseGroup').onclick=()=>releaseSelectedGroup();$('prefSplitGroup').onclick=()=>splitSelectedGroup();$('prefCloseSplit').onclick=()=>sd.close();$('priorityTabs').querySelectorAll('[data-priority]').forEach(b=>b.onclick=()=>{activePriority=Number(b.dataset.priority);selectedGroup=null;touchSelection=null;renderEditor()})}
function currentList(){return listById(currentListId)}function currentSeats(){const l=currentList();return l?.layout?YNLayout.buildSeats(l.layout):[]}function currentAssignments(){return assignments(currentListId,activePriority)}function groupRows(group){return currentAssignments().filter(a=>a.seat_group===group)}function segment(target){return currentSeats().filter(s=>s.section===target.section&&s.segment===target.segment).sort((a,b)=>a.order-b.order)}function rowOrder(section,rowRef,areaId){return YNLayout.rowOrder(currentSeats(),section,rowRef,areaId)}
function freeRun(target,ignoreGroup=null){const line=segment(target),idx=line.findIndex(s=>s.id===target.id),occ=new Set(currentAssignments().filter(a=>a.seat_group!==ignoreGroup).map(a=>a.seat_id));if(idx<0||occ.has(target.id))return[];let l=idx,r=idx;while(l>0&&!occ.has(line[l-1].id))l--;while(r<line.length-1&&!occ.has(line[r+1].id))r++;return line.slice(l,r+1)}
function chooseFrom(target,n,ignoreGroup=null){const run=freeRun(target,ignoreGroup);if(run.length<n)return{chosen:run,available:run.length};const idx=run.findIndex(s=>s.id===target.id),start=Math.min(Math.max(0,idx),run.length-n);return{chosen:run.slice(start,start+n),available:run.length}}
function addGroup(section,seats,group=uid('pref')){const a=currentAssignments(),existing=new Set(a.map(x=>x.seat_id));for(const s of seats)if(!existing.has(s.id))a.push({seat_id:s.id,section,seat_group:group});setAssignments(currentListId,activePriority,a);return group}function deleteGroup(group){setAssignments(currentListId,activePriority,currentAssignments().filter(a=>a.seat_group!==group))}
function ghost(n){const g=document.createElement('div');g.className='ghost';for(let i=0;i<n;i++)g.appendChild(document.createElement('span'));document.body.appendChild(g);return g}function startFragDrag(e,el){const d={kind:'request',section:el.dataset.section,index:+el.dataset.index,count:+el.dataset.count};e.dataTransfer.setData('application/json',JSON.stringify(d));const g=ghost(d.count);e.dataTransfer.setDragImage(g,8,16);setTimeout(()=>g.remove(),0)}function startGroupDrag(e,el){const group=el.dataset.group,n=groupRows(group).length;e.dataTransfer.setData('application/json',JSON.stringify({kind:'group',group,count:n}));const g=ghost(n);e.dataTransfer.setDragImage(g,8,16);setTimeout(()=>g.remove(),0)}
function openPreSplit(sec,index,count){if(count<2)return;const d=$('prefSplitDialog'),c=$('prefSplitChoices');$('prefSplitText').textContent=`פיצול ${count} מקומות`;c.innerHTML='';for(let n=1;n<count;n++){const b=document.createElement('button');b.type='button';b.textContent=`${n} + ${count-n}`;b.onclick=()=>{const a=[...getFrags(currentListId,activePriority,sec)];a.splice(index,1,n,count-n);setFrags(currentListId,activePriority,sec,a);d.close();renderEditor()};c.appendChild(b)}d.showModal()}
async function placeRequest(d,target){if(d.section!==target.section)return alert('יש לשבץ בצד המתאים.');const x=chooseFrom(target,d.count);if(!x.chosen.length)return alert('אין כאן מקום פנוי בעדיפות זו.');const a=[...getFrags(currentListId,activePriority,d.section)];if(x.chosen.length<d.count){if(!confirm(`יש כאן רק ${x.chosen.length} מקומות רצופים. לפצל ${d.count} ל־${x.chosen.length}+${d.count-x.chosen.length}?`))return;a.splice(d.index,1,d.count-x.chosen.length);addGroup(d.section,x.chosen);setFrags(currentListId,activePriority,d.section,a)}else{a.splice(d.index,1);addGroup(d.section,x.chosen);setFrags(currentListId,activePriority,d.section,a)}touchSelection=null;renderEditor();renderPrefSummary(currentListId)}
async function placeGroup(d,target){const cur=groupRows(d.group);if(!cur.length||cur[0].section!==target.section)return alert('יש להזיז קבוצה בתוך אותו צד.');const x=chooseFrom(target,cur.length,d.group);if(!x.chosen.length)return alert('אין כאן מקום פנוי.');if(x.chosen.length<cur.length){if(!confirm(`יש כאן רק ${x.chosen.length} מקומות רצופים. לפצל את הקבוצה?`))return;const seats=currentSeats(),firstSeat=seats.find(s=>s.id===cur[0].seat_id),ord=rowOrder(cur[0].section,firstSeat?.row_id,firstSeat?.area_id);const sorted=[...cur].sort((a,b)=>ord.findIndex(x=>x.id===a.seat_id)-ord.findIndex(x=>x.id===b.seat_id)),moving=sorted.slice(0,x.chosen.length),movingIds=new Set(moving.map(a=>a.seat_id));const remaining=currentAssignments().filter(a=>!(a.seat_group===d.group&&movingIds.has(a.seat_id)));setAssignments(currentListId,activePriority,remaining);addGroup(cur[0].section,x.chosen,uid('pref'));touchSelection=null;selectedGroup=null;renderEditor();renderPrefSummary(currentListId);return}deleteGroup(d.group);addGroup(cur[0].section,x.chosen,d.group);touchSelection=null;selectedGroup=null;renderEditor();renderPrefSummary(currentListId)}
function dropSeat(e){e.preventDefault();let d;try{d=JSON.parse(e.dataTransfer.getData('application/json'))}catch{return}const t=currentSeats().find(s=>s.id===e.currentTarget.dataset.seat);if(!t)return;if(d.kind==='request')placeRequest(d,t);else if(d.kind==='group')placeGroup(d,t)}
function selectGroup(group){selectedGroup=group;const a=groupRows(group);if(!a.length)return;$('prefGroupTitle').textContent=`${priorityName(activePriority)} — ${a.length} מקומות`;$('prefSplitCount').innerHTML='';for(let i=1;i<a.length;i++)$('prefSplitCount').insertAdjacentHTML('beforeend',`<option>${i}</option>`);$('prefSplitGroup').style.display=a.length>1?'inline-block':'none';$('prefGroupTools').classList.add('show');renderMap()}
function splitSelectedGroup(){const a=groupRows(selectedGroup),n=+$('prefSplitCount').value;if(a.length<2||!n)return;const seats=currentSeats(),first=seats.find(s=>s.id===a[0].seat_id),ord=rowOrder(a[0].section,first?.row_id,first?.area_id);const sorted=[...a].sort((x,y)=>ord.findIndex(z=>z.id===x.seat_id)-ord.findIndex(z=>z.id===y.seat_id)),move=new Set(sorted.slice(n).map(x=>x.seat_id)),ng=uid('pref');for(const x of currentAssignments())if(x.seat_group===selectedGroup&&move.has(x.seat_id))x.seat_group=ng;selectedGroup=null;$('prefGroupTools').classList.remove('show');renderEditor();renderPrefSummary(currentListId)}
function releaseSelectedGroup(){if(!selectedGroup)return;if(!confirm('לשחרר את הקבוצה מעדיפות זו?'))return;deleteGroup(selectedGroup);selectedGroup=null;$('prefGroupTools').classList.remove('show');resetFragsForList(currentListId);renderEditor();renderPrefSummary(currentListId)}
function clearPriority(){if(!currentListId||!currentAssignments().length)return;if(!confirm(`לנקות את כל ${priorityName(activePriority)}?`))return;setAssignments(currentListId,activePriority,[]);resetFragsForList(currentListId);selectedGroup=null;touchSelection=null;renderEditor();renderPrefSummary(currentListId)}
function otherPriorityMarks(seatId){const marks=[];for(let p=1;p<=3;p++)if(p!==activePriority&&assignments(currentListId,p).some(a=>a.seat_id===seatId))marks.push(`<span class="otherPriorityMark priority${p}">${p}</span>`);return marks.length?`<span class="otherPriorityMarks">${marks.join('')}</span>`:''}
function seatHtml(s){const a=currentAssignments().find(x=>x.seat_id===s.id);let cls=` prefPriority${activePriority}`,attrs='',lab='';if(a){cls+=' taken';attrs=`draggable="true" data-group="${esc(a.seat_group)}"`;if(a.seat_group===selectedGroup)cls+=' selected'}if(a){const all=groupRows(a.seat_group),ord=rowOrder(s.section,s.row_id,s.area_id).filter(x=>all.some(y=>y.seat_id===x.id)),p=ord.findIndex(x=>x.id===s.id);if(p===Math.floor((ord.length-1)/2))lab=`<span class="gname">${priorityName(activePriority)}</span>`}return `<div class="seat${cls}" data-seat="${esc(s.id)}" ${attrs}>${lab}${otherPriorityMarks(s.id)}</div>`}
function gridCellHtml(area,r,c,cell){if(cell.type==='seat'){const s=currentSeats().find(x=>x.area_id===area.id&&x.row===r+1&&x.col===c+1);return s?seatHtml(s):'<div class="seat unavailable"></div>'}if(cell.type==='stage')return `<div class="stageCell">${esc(cell.label||'במה')}</div>`;return `<div class="${cell.type==='aisle'?'aisleCell':'spacerCell'}"></div>`}
function areaRowHtml(area,r){const row=area.grid.cells[r]||[];return `<div class="row areaRow"><span class="rn">${r+1}</span><div class="rowseats" data-area="${esc(area.id)}" data-row="${r+1}">${row.map((cell,c)=>gridCellHtml(area,r,c,cell)).join('')}</div></div>`}
function areaHtml(area){const sex=area.section==='women'?'נשים':'גברים';return `<section class="seatArea" data-area="${esc(area.id)}" data-section="${area.section}"><div class="areaTitle"><b>${esc(area.name)}</b><span>${sex}</span></div><div class="areaMap">${Array.from({length:area.grid.rows},(_,r)=>areaRowHtml(area,r)).join('')}</div></section>`}
function levelHtml(level){const buckets={front:[],left:[],center:[],right:[],rear:[]};for(const a of level.areas)(buckets[a.position]||buckets.center).push(a);const slot=(pos,label)=>`<div class="areaSlot position-${pos}" data-position="${pos}">${buckets[pos].length?buckets[pos].map(areaHtml).join(''):`<div class="emptyAreaSlot">${label}</div>`}</div>`;return `<section class="levelSeatMap" data-level="${esc(level.id)}"><h3>${esc(level.name)}</h3><div class="areasCanvas">${slot('front','קדמי')}${slot('left','שמאל')}${slot('center','מרכז')}${slot('right','ימין')}${slot('rear','אחורי')}</div></section>`}
function renderMap(){const l=currentList();if(!l?.layout)return;const d=YNLayout.toAreaDefinition(l.layout),map=$('prefLayoutMap');map.innerHTML=d.levels.map(levelHtml).join('');map.querySelectorAll('.seat[data-seat]').forEach(el=>{el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',dropSeat);if(el.dataset.group)el.addEventListener('dragstart',e=>startGroupDrag(e,el));el.addEventListener('click',e=>{const target=currentSeats().find(s=>s.id===el.dataset.seat);if(!target)return;if(touchSelection){e.preventDefault();e.stopPropagation();const d=clone(touchSelection);touchSelection=null;if(d.kind==='request')placeRequest(d,target);else placeGroup(d,target);return}if(el.dataset.group)selectGroup(el.dataset.group)})})}
function renderRequestSide(sec){const box=$(sec==='men'?'prefMenRequests':'prefWomenRequests'),need=countFor(currentListId,sec),got=assignedCount(currentListId,activePriority,sec),rem=Math.max(0,need-got),fs=getFrags(currentListId,activePriority,sec);if(!need){box.innerHTML='<div class="prefEmpty">לא התבקשו מקומות בצד זה.</div>';return}box.innerHTML=`<div class="family"><div class="fname">${esc($('family').value.trim()||'המשפחה')}</div><div class="frags">${fs.map((n,i)=>`<div class="fragwrap"><div class="frag" draggable="true" data-section="${sec}" data-index="${i}" data-count="${n}">${Array.from({length:n},()=>'<span class="fseat"></span>').join('')}</div>${n>1?`<button class="splitmini" type="button" data-section="${sec}" data-index="${i}" data-count="${n}">פצל</button>`:''}</div>`).join('')}</div><div class="progress">שובצו ${got} מתוך ${need}${rem?' · נותרו '+rem:''}</div></div>`;box.querySelectorAll('.frag').forEach(el=>{el.addEventListener('dragstart',e=>startFragDrag(e,el));el.addEventListener('click',()=>{touchSelection={kind:'request',section:el.dataset.section,index:+el.dataset.index,count:+el.dataset.count};$('prefEditorStatus').textContent=`נבחרה קבוצה של ${el.dataset.count} מקומות. לחצו על כיסא יעד.`})});box.querySelectorAll('.splitmini').forEach(b=>b.onclick=()=>openPreSplit(b.dataset.section,+b.dataset.index,+b.dataset.count))}
function renderPriorityTabs(){$('priorityTabs').querySelectorAll('[data-priority]').forEach(b=>{const p=Number(b.dataset.priority),n=assignments(currentListId,p).length,complete=priorityComplete(currentListId,p)&&requestedTotal(currentListId)>0;b.classList.toggle('active',p===activePriority);b.classList.toggle('complete',complete);b.innerHTML=`עדיפות ${p}<small>${n}/${requestedTotal(currentListId)}</small>`})}
function renderEditor(){const l=currentList();if(!l?.layout)return;$('seatPrefTitle').textContent=`${l.title} — בחירת חלופות מועדפות`;const f=l.layout.definition?.front||{};$('prefFrontLeft').textContent=f.left||'';$('prefFrontCenter').textContent=f.center||'';$('prefFrontRight').textContent=f.right||'';renderPriorityTabs();renderRequestSide('women');renderRequestSide('men');renderMap();const men=assignedCount(currentListId,activePriority,'men'),women=assignedCount(currentListId,activePriority,'women'),needMen=countFor(currentListId,'men'),needWomen=countFor(currentListId,'women');$('prefPriorityProgress').innerHTML=`<span class="priorityProgress priority${activePriority}"><b>${priorityName(activePriority)}</b> גברים ${men}/${needMen} · נשים ${women}/${needWomen}${priorityComplete(currentListId,activePriority)?' · הושלמה':' · עדיין לא הושלמה'}</span>`;if(!selectedGroup)$('prefGroupTools').classList.remove('show')}
function openPrefDialog(listId){ensurePrefDialog();const l=listById(listId);if(!l?.layout)return;if(countFor(l.id,'men')<=0&&countFor(l.id,'women')<=0){alert('לפני בחירת מקום, הזינו כמה מקומות נדרשים לגברים ו/או לנשים ברשימה זו.');return}currentListId=String(l.id);activePriority=1;selectedGroup=null;touchSelection=null;renderEditor();$('seatPrefDialog').showModal()}
function validatePlans(){for(const l of lists){const total=requestedTotal(l.id),used=[];for(let p=1;p<=3;p++)if(priorityUsed(l.id,p))used.push(p);if(used.length){for(let i=0;i<used.length;i++)if(used[i]!==i+1)return `ברשימה "${l.title}" יש למלא את העדיפויות ברצף, החל מעדיפות 1.`;for(const p of used)if(!priorityComplete(l.id,p))return `ברשימה "${l.title}", ${priorityName(p)} אינה מלאה. יש לשבץ בה את כל ${total} המקומות המבוקשים.`}}return''}
async function renderAuth(){const seq=++authSeq,{data:{session}}=await db.auth.getSession();if(seq!==authSeq)return;const login=$('googleLogin'),signed=$('signedIn'),who=$('who'),admin=$('adminLink');if(session?.user){login.style.display='none';signed.style.display='block';who.textContent='מחובר: '+(session.user.email||'');const ok=await isAdmin(db,session);if(seq!==authSeq)return;const a=YNGeneric.getAccess?.();admin.style.display=ok?'inline-block':'none';if(ok){const slug=a?.current?.slug||org;admin.href='admin.html'+(slug?'?org='+encodeURIComponent(slug):'')}}else{login.style.display='inline-block';signed.style.display='none';admin.style.display='none'}}
$('googleLogin').onclick=async()=>{const redirect=SITE+(org?'?org='+encodeURIComponent(org):'');const {error}=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo:redirect}});if(error)alert('לא ניתן להתחבר כרגע: '+error.message)};$('logout').onclick=async()=>{await db.auth.signOut()};db.auth.onAuthStateChange(()=>{clearTimeout(authTimer);authTimer=setTimeout(renderAuth,75)});$('family').oninput=()=>{lastLookup='';clearTimeout(timer);lookupController?.abort();lookupSeq++;timer=setTimeout(lookup,650)};$('family').onblur=()=>{clearTimeout(timer);timer=null;lookup()};
$('form').onsubmit=async e=>{e.preventDefault();const name=$('family').value.trim().replace(/\s+/g,' ');if(!name)return msg('יש להזין שם משפחה.',true);const entries=[],seat_preferences=[],planError=validatePlans();if(planError)return msg(planError,true);for(const l of lists){const men=val('men-'+l.id),women=val('women-'+l.id);if(men===null||women===null)return msg('יש להזין מספר שלם בין 0 ל־100 בכל השדות.',true);entries.push({request_list_id:l.id,men,women});if(l.layout){for(let p=1;p<=3;p++)for(const a of assignments(l.id,p))seat_preferences.push({request_list_id:l.id,layout_id:l.layout.id,seat_id:a.seat_id,priority:p,seat_group:a.seat_group||null})}}const save=$('save');save.disabled=true;save.textContent='שומר...';try{lookupController?.abort();lookupSeq++;await call(FN,{method:'POST',body:JSON.stringify({family_name:name,notes:$('notes').value.trim(),entries,seat_preferences})});$('existing').classList.add('show');msg('הרישום והעדפות המקום נשמרו בהצלחה.');lastLookup=name}catch(e){const m=String(e.message||''),text=m==='One or more request lists are closed'?'אחת הרשימות נסגרה לרישום. רעננו את הדף ונסו שוב.':m==='Seat preference layout is unavailable'?'תצורת האולם השתנתה. רעננו את הדף ובחרו שוב את המקומות.':m==='Seat preference priority is incomplete'?'אחת מעדיפויות המקום אינה כוללת את כל מספר המקומות המבוקש.':'לא הצלחנו לשמור את הרישום. נסו שוב.';msg(text,true)}finally{save.disabled=!lists.length;save.textContent='שמירת הרישום'}};
loadLists();renderAuth();
})();