(()=>{
const {SITE,makeClient,isAdmin,uid,esc}=YNGeneric,{normalizeDefinition,buildSeats:engineSeats,rowOrder:engineRowOrder}=YNLayout,db=makeClient(),$=id=>document.getElementById(id);
const S={session:null,lists:[],layouts:[],listId:null,layoutId:null,layout:null,reqs:[],assignments:[],seats:[],selectedGroup:null};
const touchMode=(navigator.maxTouchPoints||0)>0||window.matchMedia('(pointer: coarse)').matches;let touchSelected=null;
const YEAR={
'אביקסיס':[{row:7,zone:'right',side:'right'}],'בלונדר':[{row:7,zone:'right',side:'left'}],'גוטליב':[{row:2,zone:'right',side:'right'}],'הר-זהב':[{row:2,zone:'right',side:'left'}],
'וידס':[{row:8,zone:'right',side:'left'}],'חן':[{row:4,zone:'right',side:'right'}],'נוב':[{row:4,zone:'left',side:'left'}],'פורת':[{row:4,zone:'left',side:'center'}],
'פישמן - זכות':[{row:5,zone:'right',side:'right'}],'צדוק':[{row:5,zone:'right',side:'left'}],'קסדו':[{row:3,zone:'left',side:'left'}],'קסנר':[{row:6,zone:'center',side:'right'}],
'רוט':[{row:8,zone:'center',side:'left'}],'שריד':[{row:2,zone:'center',side:'left'}],'שטרק 1':[{row:1,zone:'left',side:'center'},{row:1,zone:'center',side:'center'}],
'צחי':[{row:8,zone:'left',side:'right'},{row:8,zone:'center',side:'right'}]
};
function setStatus(t){$('status').textContent=t||''}
function currentList(){return S.lists.find(x=>x.id===S.listId)||null}function currentLayout(){return S.layouts.find(x=>x.id===S.layoutId)||null}
function requestCount(familyId,sec){const r=S.reqs.find(x=>x.family_id===familyId);return Number(sec==='men'?r?.men:r?.women)||0}
function assignedCount(familyId,sec){return S.assignments.filter(a=>a.family_id===familyId&&a.section===sec).length}
function rowOrder(sec,rowRef){return engineRowOrder(S.seats,sec,rowRef)}
function familyName(id){return S.reqs.find(r=>r.family_id===id)?.family_name||S.assignments.find(a=>a.family_id===id)?.family_name||''}
function groupId(){return uid('g')}
function fragKey(f,s){return `seatplan-frag:${S.listId}:${S.layoutId}:${s}:${f}`}
function getFrags(f,s,remaining){if(remaining<=0)return[];try{const a=JSON.parse(localStorage.getItem(fragKey(f,s))||'[]');if(Array.isArray(a)&&a.every(n=>Number.isInteger(n)&&n>0)&&a.reduce((x,y)=>x+y,0)===remaining)return a}catch{}return[remaining]}
function setFrags(f,s,a){localStorage.setItem(fragKey(f,s),JSON.stringify(a))}
async function gate(){const {data:{session}}=await db.auth.getSession();S.session=session;if(!session?.user||!(await isAdmin(db,session))){$('loginGate').innerHTML='יש להתחבר כמנהל כדי להשתמש בסידור ההושבה. <button id="seatLogin" class="btn primary">התחבר עם Google</button>';$('seatLogin').onclick=()=>db.auth.signInWithOAuth({provider:'google',options:{redirectTo:SITE+'seating.html'}});$('app').classList.add('hidden');return false}$('loginGate').classList.add('hidden');$('app').classList.remove('hidden');return true}
async function loadMeta(){
 const [lr,yr]=await Promise.all([db.from('yamim_noraim_request_lists').select('id,code,title,sort_order,is_active').eq('is_active',true).order('sort_order').order('created_at'),db.from('yamim_noraim_layouts').select('id,code,title,definition,sort_order,is_active').eq('is_active',true).order('sort_order').order('created_at')]);if(lr.error)throw lr.error;if(yr.error)throw yr.error;S.lists=lr.data||[];S.layouts=(yr.data||[]).map(x=>({...x,definition:normalizeDefinition(x.definition)}));
 const url=new URL(location.href),ql=url.searchParams.get('list'),qy=url.searchParams.get('layout');S.listId=[ql,localStorage.getItem('yn:list'),S.listId].find(x=>S.lists.some(l=>l.id===x))||S.lists[0]?.id||null;S.layoutId=[qy,localStorage.getItem('yn:layout'),S.layoutId].find(x=>S.layouts.some(l=>l.id===x))||S.layouts[0]?.id||null;renderSelectors();
}
function renderSelectors(){const ls=$('requestListSelect'),ys=$('layoutSelect');ls.innerHTML=S.lists.map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join('');ys.innerHTML=S.layouts.map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join('');if(S.listId)ls.value=S.listId;if(S.layoutId)ys.value=S.layoutId}
async function load(){
 S.selectedGroup=null;touchSelected=null;$('tools').classList.remove('show');if(!S.listId||!S.layoutId){S.reqs=[];S.assignments=[];S.seats=[];render();return setStatus('יש להגדיר לפחות רשימת בקשות ותצורה אחת.')}
 setStatus('טוען...');S.layout=currentLayout();S.seats=engineSeats(S.layout);
 const [rr,ar]=await Promise.all([db.from('yamim_noraim_requests').select('family_id,men,women,updated_at').eq('request_list_id',S.listId),db.from('yamim_noraim_seating_v2').select('id,family_id,section,seat_id,seat_group,created_at,updated_at').eq('request_list_id',S.listId).eq('layout_id',S.layoutId)]);if(rr.error)throw rr.error;if(ar.error)throw ar.error;
 const req=rr.data||[],ids=[...new Set(req.map(x=>x.family_id))];let fam=[];if(ids.length){const f=await db.from('yamim_noraim_families').select('id,family_name,notes').in('id',ids);if(f.error)throw f.error;fam=f.data||[]}const fm=new Map(fam.map(x=>[x.id,x]));S.reqs=req.map(x=>({...x,family_name:fm.get(x.family_id)?.family_name||'',notes:fm.get(x.family_id)?.notes||''})).sort((a,b)=>a.family_name.localeCompare(b.family_name,'he'));S.assignments=(ar.data||[]).map(a=>({...a,family_name:fm.get(a.family_id)?.family_name||''}));
 const valid=new Set(S.seats.map(s=>s.id));const dangling=S.assignments.filter(a=>!valid.has(a.seat_id)).length;render();setStatus(dangling?`יש ${dangling} שיבוצים ישנים שאינם קיימים בתצורה הנוכחית. ערוך את התצורה או נקה את השיבוץ.`:'השינויים נשמרים אוטומטית.');
}
async function createGroup(familyId,section,seats,g=groupId()){if(!seats.length)return g;const rows=seats.map(seat=>({request_list_id:S.listId,layout_id:S.layoutId,family_id:familyId,section,seat_id:seat.id,seat_group:g}));const {error}=await db.from('yamim_noraim_seating_v2').insert(rows);if(error)throw error;return g}
async function deleteGroup(g){const {error}=await db.from('yamim_noraim_seating_v2').delete().eq('request_list_id',S.listId).eq('layout_id',S.layoutId).eq('seat_group',g);if(error)throw error}
async function deleteAssignment(id){const {error}=await db.from('yamim_noraim_seating_v2').delete().eq('id',id);if(error)throw error}
async function patchGroup(id,g){const {error}=await db.from('yamim_noraim_seating_v2').update({seat_group:g,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error}
function segment(target){return S.seats.filter(s=>s.section===target.section&&s.segment===target.segment).sort((a,b)=>a.order-b.order)}
function freeRun(target,ignore=null){const line=segment(target),idx=line.findIndex(s=>s.id===target.id),occ=new Set(S.assignments.filter(a=>(a.seat_group||a.id)!==ignore).map(a=>a.seat_id));if(idx<0||occ.has(target.id))return[];let l=idx,r=idx;while(l>0&&!occ.has(line[l-1].id))l--;while(r<line.length-1&&!occ.has(line[r+1].id))r++;return line.slice(l,r+1)}
function chooseFrom(target,n,ignore=null){const run=freeRun(target,ignore);if(run.length<n)return{chosen:run,available:run.length};const idx=run.findIndex(s=>s.id===target.id),start=Math.min(Math.max(0,idx),run.length-n);return{chosen:run.slice(start,start+n),available:run.length}}
function render(){renderFront();renderRequests('women');renderRequests('men');renderMaps();const nm=S.reqs.reduce((x,r)=>x+(Number(r.men)||0),0),nw=S.reqs.reduce((x,r)=>x+(Number(r.women)||0),0);$('sumFamilies').textContent=S.reqs.filter(r=>(r.men||0)+(r.women||0)>0).length+' משפחות';$('sumMen').textContent=`גברים ${S.assignments.filter(a=>a.section==='men').length}/${nm} · ${S.seats.filter(s=>s.section==='men').length} כיסאות`;$('sumWomen').textContent=`נשים ${S.assignments.filter(a=>a.section==='women').length}/${nw} · ${S.seats.filter(s=>s.section==='women').length} כיסאות`;bindTouch()}
function renderFront(){const f=S.layout?.definition?.front||{};$('frontLeft').textContent=f.left||'';$('frontCenter').textContent=f.center||'';$('frontRight').textContent=f.right||''}
function renderRequests(sec){const box=$(sec==='men'?'menRequests':'womenRequests');box.innerHTML=S.reqs.filter(r=>requestCount(r.family_id,sec)>0).map(r=>{const need=requestCount(r.family_id,sec),got=assignedCount(r.family_id,sec),rem=Math.max(0,need-got),fr=getFrags(r.family_id,sec,rem);return `<div class="family"><div class="fname">${esc(r.family_name)}</div><div class="frags">${fr.map((n,i)=>`<div class="fragwrap"><div class="frag" draggable="true" data-family-id="${r.family_id}" data-family="${esc(r.family_name)}" data-section="${sec}" data-index="${i}" data-count="${n}">${Array.from({length:n},()=>'<span class="fseat"></span>').join('')}</div>${n>1?`<button class="splitmini" data-family-id="${r.family_id}" data-section="${sec}" data-index="${i}" data-count="${n}">פצל</button>`:''}</div>`).join('')}</div><div class="progress">שובצו ${got} מתוך ${need}${rem?' · נותרו '+rem:''}</div>${r.notes?`<div class="note">${esc(r.notes)}</div>`:''}</div>`}).join('');box.querySelectorAll('.frag').forEach(el=>el.addEventListener('dragstart',e=>startFragDrag(e,el)));box.querySelectorAll('.splitmini').forEach(b=>b.onclick=()=>openPreSplit(b.dataset.familyId,b.dataset.section,+b.dataset.index,+b.dataset.count))}
function ghost(n){const g=document.createElement('div');g.className='ghost';for(let i=0;i<n;i++)g.appendChild(document.createElement('span'));document.body.appendChild(g);return g}
function startFragDrag(e,el){const d={kind:'request',familyId:el.dataset.familyId,family:el.dataset.family,section:el.dataset.section,index:+el.dataset.index,count:+el.dataset.count};e.dataTransfer.setData('application/json',JSON.stringify(d));const g=ghost(d.count);e.dataTransfer.setDragImage(g,8,16);setTimeout(()=>g.remove(),0)}
function openPreSplit(f,s,index,count){if(count<2)return;const d=$('splitDialog'),c=$('splitChoices');$('splitText').textContent=`פיצול ${familyName(f)}: ${count} מקומות`;c.innerHTML='';for(let n=1;n<count;n++){const b=document.createElement('button');b.className='btn';b.textContent=`${n} + ${count-n}`;b.onclick=()=>{const rem=Math.max(0,requestCount(f,s)-assignedCount(f,s)),a=getFrags(f,s,rem);a.splice(index,1,n,count-n);setFrags(f,s,a);d.close();renderRequests(s);bindTouch()};c.appendChild(b)}d.showModal()}
function cellHtml(sec,row,cell){if(cell.type==='seats'){const list=S.seats.filter(s=>s.section===sec&&s.row_id===row.id&&s.cell_id===cell.id).sort((a,b)=>a.seat_index-b.seat_index);return `<div class="block">${list.map(seatHtml).join('')}</div>`}const width=Number(cell.width)||1;if(cell.type==='stage')return `<div class="stageCell" style="width:calc(var(--seat) * ${width})">${esc(cell.label||'במה')}</div>`;return `<div class="${cell.type==='aisle'?'aisleCell':'spacerCell'}" style="width:calc(var(--seat) * ${width})"></div>`}
function rowHtml(sec,row){return `<div class="row"><span class="rn">${esc(row.label)}</span><div class="rowseats">${row.cells.map(c=>cellHtml(sec,row,c)).join('')}</div></div>`}
function seatHtml(s){const a=S.assignments.find(x=>x.seat_id===s.id);let cls='',lab='',g='';if(a){cls=' taken';g=a.seat_group||a.id;const all=S.assignments.filter(x=>(x.seat_group||x.id)===g),ord=rowOrder(s.section,s.row_id).filter(x=>all.some(y=>y.seat_id===x.id)),p=ord.findIndex(x=>x.id===s.id);if(p===Math.floor((ord.length-1)/2))lab=`<span class="gname">${esc(a.family_name)}</span>`;if(g===S.selectedGroup)cls+=' selected'}return `<div class="seat${cls}" data-seat="${s.id}" ${a?`draggable="true" data-group="${esc(g)}"`:''}>${lab}</div>`}
function renderMaps(){for(const sec of ['women','men']){const def=S.layout?.definition?.sections?.[sec],map=$(sec+'Map');map.innerHTML=(def?.rows||[]).map(r=>rowHtml(sec,r)).join('')}document.querySelectorAll('.seat[data-seat]').forEach(el=>{el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',dropSeat);if(el.dataset.group){el.addEventListener('dragstart',e=>startGroupDrag(e,el));el.onclick=()=>selectGroup(el.dataset.group)}})}
async function dropSeat(e){e.preventDefault();let d;try{d=JSON.parse(e.dataTransfer.getData('application/json'))}catch{return}const t=S.seats.find(s=>s.id===e.currentTarget.dataset.seat);if(!t)return;if(d.kind==='request')return placeRequest(d,t);if(d.kind==='group')return placeGroup(d,t)}
async function placeRequest(d,t){if(d.section!==t.section)return alert('יש לשבץ בצד המתאים.');const x=chooseFrom(t,d.count);if(!x.chosen.length)return alert('אין כאן מקום פנוי.');const rem=Math.max(0,requestCount(d.familyId,d.section)-assignedCount(d.familyId,d.section)),a=getFrags(d.familyId,d.section,rem);if(x.chosen.length<d.count){if(!confirm(`יש כאן רק ${x.chosen.length} מקומות רצופים. לפצל ${d.count} ל־${x.chosen.length}+${d.count-x.chosen.length}?`))return;a.splice(d.index,1,d.count-x.chosen.length);await createGroup(d.familyId,d.section,x.chosen);setFrags(d.familyId,d.section,a)}else{a.splice(d.index,1);await createGroup(d.familyId,d.section,x.chosen);setFrags(d.familyId,d.section,a)}await load()}
function startGroupDrag(e,el){const g=el.dataset.group,n=S.assignments.filter(a=>(a.seat_group||a.id)===g).length;e.dataTransfer.setData('application/json',JSON.stringify({kind:'group',group:g,count:n}));const x=ghost(n);e.dataTransfer.setDragImage(x,8,16);setTimeout(()=>x.remove(),0)}
async function placeGroup(d,t){const cur=S.assignments.filter(a=>(a.seat_group||a.id)===d.group);if(!cur.length||cur[0].section!==t.section)return alert('יש להזיז קבוצה בתוך אותו צד.');const x=chooseFrom(t,cur.length,d.group);if(!x.chosen.length)return alert('אין כאן מקום פנוי.');if(x.chosen.length<cur.length){if(!confirm(`יש כאן רק ${x.chosen.length} מקומות רצופים. לפצל את הקבוצה?`))return;return splitAndMove(cur,x.chosen)}const fam=cur[0].family_id,sec=cur[0].section;await deleteGroup(d.group);await createGroup(fam,sec,x.chosen,d.group);await load()}
async function splitAndMove(cur,chosen){const objs=cur.map(x=>S.seats.find(s=>s.id===x.seat_id)).filter(Boolean),ord=rowOrder(cur[0].section,objs[0]?.row_id),sorted=[...cur].sort((a,b)=>ord.findIndex(x=>x.id===a.seat_id)-ord.findIndex(x=>x.id===b.seat_id)),moving=sorted.slice(0,chosen.length),ng=groupId();for(const a of moving)await deleteAssignment(a.id);await createGroup(cur[0].family_id,cur[0].section,chosen,ng);await load()}
function selectGroup(g){S.selectedGroup=g;const a=S.assignments.filter(x=>(x.seat_group||x.id)===g);if(!a.length)return;$('groupTitle').textContent=`${a[0].family_name} — ${a.length} מקומות`;$('splitCount').innerHTML='';for(let i=1;i<a.length;i++)$('splitCount').insertAdjacentHTML('beforeend',`<option>${i}</option>`);$('splitBtn').style.display=a.length>1?'inline-block':'none';$('tools').classList.add('show');renderMaps();bindTouch()}
async function splitGroup(){const a=S.assignments.filter(x=>(x.seat_group||x.id)===S.selectedGroup),n=+$('splitCount').value;if(a.length<2)return;const objs=a.map(x=>S.seats.find(s=>s.id===x.seat_id)).filter(Boolean),ord=rowOrder(a[0].section,objs[0]?.row_id);objs.sort((x,y)=>ord.findIndex(z=>z.id===x.id)-ord.findIndex(z=>z.id===y.id));const ids=new Set(objs.slice(n).map(s=>s.id)),ng=groupId();for(const x of a.filter(q=>ids.has(q.seat_id)))await patchGroup(x.id,ng);await load()}
async function clearCurrent(){if(!confirm(`לאפס את כל השיבוצים ברשימה "${currentList()?.title||''}" ובתצורה "${currentLayout()?.title||''}"?`))return;const {error}=await db.from('yamim_noraim_seating_v2').delete().eq('request_list_id',S.listId).eq('layout_id',S.layoutId);if(error)return alert(error.message);await load()}
function noteRules(note,sec){const n=String(note||''),r={row:null,strong:false,near:null};const womenOnly=/נשים[^\n]*שורה|שורה[^\n]*נשים/.test(n),menOnly=/גברים[^\n]*שורה|שורה[^\n]*גברים/.test(n);if((!womenOnly||sec==='women')&&(!menOnly||sec==='men')){if(/שורה\s*(ה)?ראשונה/.test(n))r.row=1;if(/שורה\s*(ה)?אחרונה/.test(n))r.row=8}if(/אותו\s*מקום|אותו\s*המקום|להישאר\s*במיקום|להשאר\s*במיקום/.test(n))r.strong=true;if(/ליד/.test(n)){const z=n.replace(/[־–—-]/g,' ').replace(/\s+/g,' ').toLowerCase();r.near=S.reqs.find(x=>z.includes(x.family_name.replace(/[־–—-]/g,' ').toLowerCase()))?.family_id||null}return r}
function allSegments(sec){const m=new Map();for(const s of S.seats.filter(x=>x.section===sec)){if(!m.has(s.segment))m.set(s.segment,[]);m.get(s.segment).push(s)}for(const a of m.values())a.sort((x,y)=>x.order-y.order);return[...m.values()]}
function windows(sec,n,occ){const out=[];for(const seg of allSegments(sec)){if(seg.length<n)continue;for(let i=0;i<=seg.length-n;i++){const w=seg.slice(i,i+n);if(w.every(s=>!occ.has(s.id)))out.push(w)}}return out}
function anchorScore(list,t){const anchors=(S.layout?.definition?.legacy_no?YEAR[t.family_name]:null)||[];if(!anchors.length)return 0;const row=Number(list[0].row_label)||list[0].row,blocks=S.seats.filter(s=>s.section===t.section&&s.row_id===list[0].row_id).map(s=>s.block),maxBlock=Math.max(0,...blocks),block=list[0].block;let best=1e9;for(const a of anchors){const wantBlock=t.section==='men'?(a.zone==='right'?0:a.zone==='center'?1:maxBlock):(a.zone==='right'?0:maxBlock);let q=Math.abs(row-a.row)*(t.rules.strong?90:45)+Math.abs(block-wantBlock)*(t.rules.strong?65:32);best=Math.min(best,q)}return best}
function candidateScore(list,t,virtual){const row=Number(list[0].row_label)||list[0].row;let score=anchorScore(list,t);if(t.rules.row!=null)score+=Math.abs(row-t.rules.row)*1000;const own=[...S.assignments.filter(a=>a.family_id===t.family_id&&a.section===t.section).map(a=>S.seats.find(s=>s.id===a.seat_id)).filter(Boolean),...(virtual.get(t.section+'|'+t.family_id)||[])];if(own.length){const avg=own.reduce((a,s)=>a+(Number(s.row_label)||s.row),0)/own.length;score+=Math.abs(row-avg)*70}if(t.rules.near){const near=[...S.assignments.filter(a=>a.family_id===t.rules.near&&a.section===t.section).map(a=>S.seats.find(s=>s.id===a.seat_id)).filter(Boolean),...(virtual.get(t.section+'|'+t.rules.near)||[])];if(near.length)score+=Math.min(...near.map(s=>Math.abs((Number(s.row_label)||s.row)-row)*20))-30}return score}
function bestWindow(t,occ,virtual,n=t.count){let best=null;for(const w of windows(t.section,n,occ)){const sc=candidateScore(w,t,virtual);if(!best||sc<best.score||(sc===best.score&&w[0].id<best.w[0].id))best={w,score:sc}}return best}
function autoTasks(){const out=[];for(const r of S.reqs)for(const section of ['men','women']){const rem=Math.max(0,requestCount(r.family_id,section)-assignedCount(r.family_id,section));if(rem)out.push({family_id:r.family_id,family_name:r.family_name,section,count:rem,rules:noteRules(r.notes,section),known:!!YEAR[r.family_name]})}out.sort((a,b)=>(!!b.rules.row-!!a.rules.row)||(!!b.rules.strong-!!a.rules.strong)||(b.known-a.known)||(b.count-a.count)||a.family_name.localeCompare(b.family_name,'he')||a.section.localeCompare(b.section));return out}
async function runAuto(){const ts=autoTasks();if(!ts.length)return alert('אין כרגע מקומות חסרים לשיבוץ.');const occ=new Set(S.assignments.map(a=>a.seat_id)),virtual=new Map(),plan=[],unplaced=[];for(const t of ts){let left=t.count,parts=[];while(left>0){let pick=bestWindow(t,occ,virtual,left);if(!pick){for(let n=left-1;n>=1&&!pick;n--)pick=bestWindow(t,occ,virtual,n)}if(!pick)break;parts.push(pick.w);pick.w.forEach(s=>occ.add(s.id));const k=t.section+'|'+t.family_id;if(!virtual.has(k))virtual.set(k,[]);virtual.get(k).push(...pick.w);left-=pick.w.length;if(parts.length>4)break}if(left)unplaced.push(`${t.family_name} (${t.section==='men'?'גברים':'נשים'}: ${left})`);for(const p of parts)plan.push({t,seats:p})}const total=plan.reduce((n,p)=>n+p.seats.length,0);if(!total)return alert('לא נמצאו מקומות פנויים מתאימים.');if(!confirm(`השיבוץ האוטומטי מציע ${total} מקומות.\nשיבוצים קיימים לא יוזזו.${unplaced.length?'\n\nלא נמצא מקום מלא ל: '+unplaced.join(', '):''}\n\nלהחיל?`))return;const b=$('autoSeatBtn');b.disabled=true;b.textContent='משבץ...';try{for(const p of plan)await createGroup(p.t.family_id,p.t.section,p.seats,'auto:'+Date.now()+':'+groupId());await load()}catch(e){alert('השיבוץ נעצר: '+e.message);await load()}finally{b.disabled=false;b.textContent='שיבוץ אוטומטי'}}
async function clearAuto(){const groups=[...new Set(S.assignments.map(a=>a.seat_group).filter(g=>String(g||'').startsWith('auto:')))];if(!groups.length)return alert('אין שיבוץ אוטומטי למחיקה.');if(!confirm(`למחוק ${groups.length} קבוצות שנוצרו אוטומטית?`))return;for(const g of groups)await deleteGroup(g);await load()}
function addMobileChrome(){if(!touchMode)return;document.body.classList.add('mobile-view-hall');if(!document.querySelector('.mobileNav')){const n=document.createElement('div');n.className='mobileNav';n.innerHTML='<button data-view="hall" class="active">תרשים</button><button data-view="men">בקשות גברים</button><button data-view="women">בקשות נשים</button>';document.querySelector('.workspace')?.before(n);n.querySelectorAll('button').forEach(b=>b.onclick=()=>{document.body.classList.remove('mobile-view-hall','mobile-view-men','mobile-view-women');document.body.classList.add('mobile-view-'+b.dataset.view);n.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b))})}if(!$('touchBar')){const b=document.createElement('div');b.id='touchBar';b.className='touchBar';b.innerHTML='<div id="touchBarText" class="touchBarText"></div><button id="touchCancel">בטל</button>';document.body.appendChild(b);$('touchCancel').onclick=clearTouch}}
function clearTouch(){touchSelected=null;document.querySelectorAll('.touchSelected,.touchTargetHint').forEach(x=>x.classList.remove('touchSelected','touchTargetHint'));if($('touchBar'))$('touchBar').style.display='none'}
function bindTouch(){if(!touchMode)return;addMobileChrome();document.querySelectorAll('.frag').forEach(el=>{if(el.dataset.tb)return;el.dataset.tb='1';el.onclick=e=>{e.preventDefault();touchSelected={kind:'request',familyId:el.dataset.familyId,family:el.dataset.family,section:el.dataset.section,index:+el.dataset.index,count:+el.dataset.count};showTouch(`${touchSelected.family} — ${touchSelected.count} מקומות. גע בכיסא היעד.`);document.body.classList.remove('mobile-view-men','mobile-view-women');document.body.classList.add('mobile-view-hall')}});document.querySelectorAll('.seat[data-seat]').forEach(el=>{if(el.dataset.tb)return;el.dataset.tb='1';el.addEventListener('click',async e=>{if(!touchSelected){if(el.dataset.group){e.stopImmediatePropagation();touchSelected={kind:'group',group:el.dataset.group};showTouch('בחר כיסא יעד להעברת הקבוצה.')}return}e.preventDefault();e.stopImmediatePropagation();const t=S.seats.find(s=>s.id===el.dataset.seat);try{if(touchSelected.kind==='request')await placeRequest({...touchSelected},t);else await placeGroup({...touchSelected},t)}finally{clearTouch()}},true)})}
function showTouch(t){$('touchBarText').textContent=t;$('touchBar').style.display='flex';document.querySelectorAll('.seat:not(.taken)').forEach(x=>x.classList.add('touchTargetHint'))}
$('requestListSelect').onchange=async e=>{S.listId=e.target.value;localStorage.setItem('yn:list',S.listId);await load()};$('layoutSelect').onchange=async e=>{S.layoutId=e.target.value;localStorage.setItem('yn:layout',S.layoutId);await load()};$('clearBtn').onclick=clearCurrent;$('autoSeatBtn').onclick=runAuto;$('clearAutoBtn').onclick=clearAuto;$('splitBtn').onclick=splitGroup;$('releaseGroup').onclick=async()=>{if(!S.selectedGroup||!confirm('לשחרר את הקבוצה?'))return;await deleteGroup(S.selectedGroup);await load()};$('closeTools').onclick=()=>{S.selectedGroup=null;$('tools').classList.remove('show');renderMaps();bindTouch()};$('closeSplit').onclick=()=>$('splitDialog').close();
window.YN={S,db,$,esc,rowOrder,requestCount,assignedCount,familyName,createGroup,deleteGroup,load,chooseFrom,groupId,setStatus};
(async()=>{if(await gate())try{await loadMeta();await load();addMobileChrome()}catch(e){setStatus('שגיאה: '+e.message)}})();
})();
