(()=>{
if(!window.YN)return;
const {S,db,$,beginDraft,cancelDraft,commitDraft,isDraft,deleteGroup,load}=YN,host=$('aiPanelHost');
if(!host)return;
let busy=false;
function lockControls(on){['requestListSelect','layoutSelect','automaticSeatBtn','lastAutoProposalBtn','clearAutomaticBtn','clearBtn','referenceSelect','referenceSaveBtn','referenceActivateBtn','referenceShowBtn','referenceDeleteBtn'].forEach(id=>{const el=$(id);if(el)el.disabled=!!on});document.body.classList.toggle('draftMode',!!on)}
function finishClose(panel){const hide=panel?.querySelector('.aiHide'),old=hide?._ynOriginalClick;if(typeof old==='function')old.call(hide);else host.innerHTML='';lockControls(false);const b=$('lastAutoProposalBtn');if(b&&!host.querySelector('.aiPanel'))b.textContent='הצג הצעה אחרונה'}
async function saveDraft(e){e?.preventDefault();e?.stopImmediatePropagation();if(busy||!isDraft())return;if(!confirm('לשמור את מצב הטיוטה הנוכחי כשיבוץ הקבוע?'))return;busy=true;const panel=host.querySelector('.aiPanel'),b=panel?.querySelector('.aiApply');if(b){b.disabled=true;b.textContent='שומר...'}try{const n=await commitDraft();finishClose(panel);alert(`השיבוץ נשמר. ${n} מקומות נמצאים כעת בשיבוץ הקבוע.`)}catch(err){alert('שמירת הטיוטה נכשלה: '+err.message);if(b){b.disabled=false;b.textContent='שמור את כל השינויים'}}finally{busy=false}}
function discardDraft(e){e?.preventDefault();e?.stopImmediatePropagation();if(busy)return;const panel=host.querySelector('.aiPanel');if(isDraft()&&!confirm('לבטל את כל השינויים שנעשו מאז פתיחת ההצעה ולחזור לשיבוץ הקודם?'))return;cancelDraft();finishClose(panel)}
function decorate(panel,data,result){panel.dataset.partialEnhanced='1';panel.classList.add('draftPanel');const state=panel.querySelector('.aiState');if(state)state.textContent='מצב טיוטה פעיל — שום שינוי לא נכתב למסד הנתונים עד ללחיצה על “שמור את כל השינויים”.';const actions=panel.querySelector('.aiActions');if(actions&&!panel.querySelector('.draftReview')){const box=document.createElement('section');box.className='draftReview';box.innerHTML=`<div class="draftReviewTitle">עריכת הצעת השיבוץ על התרשים</div><div class="draftReviewText">כל ההצעה נטענה כטיוטה. אפשר לגרור שיבוצים מוצעים, להזיז שיבוצים שהיו קודם, לפצל או לשחרר קבוצות. שיבוץ מוצע מסומן בסגול; שיבוץ קיים נשאר ירוק.</div><div class="draftLegend"><span><i class="draftSwatch existing"></i>שיבוץ שהיה קיים</span><span><i class="draftSwatch proposal"></i>הצעה אוטומטית</span></div><div class="draftStats">נטענו ${result.groups||0} קבוצות מוצעות · ${result.seats||0} מקומות</div>`;actions.before(box)}const apply=panel.querySelector('.aiApply');if(apply){apply.disabled=false;apply.textContent='שמור את כל השינויים';apply.addEventListener('click',saveDraft,true)}const hide=panel.querySelector('.aiHide');if(hide){hide._ynOriginalClick=hide.onclick;hide.textContent='חזור למצב הקודם';hide.addEventListener('click',discardDraft,true)}lockControls(true)}
async function enhance(){const panel=host.querySelector('.aiPanel');if(!panel||panel.dataset.partialEnhanced||busy)return;panel.dataset.partialEnhanced='loading';const listId=S.listId,layoutId=S.layoutId;const {data,error}=await db.from('yamim_noraim_automatic_proposals').select('source,plan,meta,created_at').eq('request_list_id',listId).eq('layout_id',layoutId).maybeSingle();if(!panel.isConnected||S.listId!==listId||S.layoutId!==layoutId)return;if(error||!data?.plan){panel.dataset.partialEnhanced='error';const st=panel.querySelector('.aiState');if(st)st.textContent='לא ניתן לטעון את ההצעה השמורה לעריכה: '+(error?.message||'אין תוכנית שמורה');const a=panel.querySelector('.aiApply');if(a)a.disabled=true;return}const result=beginDraft(data.plan,data.source||'algorithm');if(!result.ok){panel.dataset.partialEnhanced='error';const st=panel.querySelector('.aiState');if(st)st.textContent='ההצעה כבר אינה תואמת לשיבוץ הנוכחי: '+result.issues.slice(0,5).join(' · ');const a=panel.querySelector('.aiApply');if(a)a.disabled=true;return}decorate(panel,data,result)}
const obs=new MutationObserver(()=>{const p=host.querySelector('.aiPanel');if(p&&!p.dataset.partialEnhanced)enhance()});obs.observe(host,{childList:true,subtree:true});if(host.querySelector('.aiPanel'))enhance();
const clearBtn=$('clearAutomaticBtn');if(clearBtn)clearBtn.addEventListener('click',async e=>{if(isDraft())return;e.preventDefault();e.stopImmediatePropagation();const groups=[...new Set(S.assignments.map(a=>a.seat_group).filter(g=>String(g||'').startsWith('auto:')||String(g||'').startsWith('ai:')||String(g||'').startsWith('proposal:')))];if(!groups.length)return alert('אין שיבוץ אוטומטי למחיקה.');if(!confirm(`למחוק ${groups.length} קבוצות שנוצרו בשיבוץ אוטומטי?\nשיבוצים ידניים יישארו.`))return;for(const g of groups)await deleteGroup(g);await load()},true);
window.addEventListener('beforeunload',e=>{if(!isDraft())return;e.preventDefault();e.returnValue=''});
})();