(()=>{
const {SITE,makeClient,isAdmin,uid,esc}=YNGeneric,{normalizeDefinition,toAreaDefinition,buildSeats:engineSeats,rowOrder:engineRowOrder}=YNLayout,db=makeClient(),$=id=>document.getElementById(id);
const S={session:null,lists:[],layouts:[],listId:null,layoutId:null,layout:null,reqs:[],assignments:[],seats:[],selectedGroup:null,editSession:null};
const touchMode=(navigator.maxTouchPoints||0)>0||window.matchMedia('(pointer: coarse)').matches;let touchSelected=null;
function setStatus(t){$('status').textContent=t||''}
function currentList(){return S.lists.find(x=>x.id===S.listId)||null}function currentLayout(){return S.layouts.find(x=>x.id===S.layoutId)||null}
function requestCount(familyId,sec){const r=S.reqs.find(x=>x.family_id===familyId);return Number(sec==='men'?r?.men:r?.women)||0}
function assignedCount(familyId,sec){return S.assignments.filter(a=>a.family_id===familyId&&a.section===sec).length}
function rowOrder(sec,rowRef,areaId=null){return engineRowOrder(S.seats,sec,rowRef,areaId)}
function familyName(id){return S.reqs.find(r=>r.family_id===id)?.family_name||S.assignments.find(a=>a.family_id===id)?.family_name||''}
function groupId(){return uid('g')}
function clone(v){return typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v))}
function fragKey(f,s){return `seatplan-frag:${S.listId}:${S.layoutId}:${s}:${f}`}
function getFrags(f,s,remaining){if(remaining<=0)return[];try{const a=JSON.parse(localStorage.getItem(fragKey(f,s))||'[]');if(Array.isArray(a)&&a.every(n=>Number.isInteger(n)&&n>0)&&a.reduce((x,y)=>x+y,0)===remaining)return a}catch{}return[remaining]}
function setFrags(f,s,a){localStorage.setItem(fragKey(f,s),JSON.stringify(a))}
async function gate(){const {data:{session}}=await db.auth.getSession();S.session=session;if(!session?.user||!(await isAdmin(db,session))){$('loginGate').innerHTML='יש להתחבר כמנהל כדי להשתמש בסידור ההושבה. <button id="seatLogin" class="btn primary">התחבר עם Google</button>';$('seatLogin').onclick=()=>db.auth.signInWithOAuth({provider:'google',options:{redirectTo:SITE+'seating.html'}});$('app').classList.add('hidden');return false}$('loginGate').classList.add('hidden');$('app').classList.remove('hidden');return true}
async function loadMeta(){
 const [lr,yr]=await Promise.all([db.from('yamim_noraim_request_lists').select('id,code,title,sort_order,is_active,default_layout_id').eq('is_active',true).order('sort_order').order('created_at'),db.from('yamim_noraim_layouts').select('id,code,title,definition,sort_order,is_active').eq('is_active',true).order('sort_order').order('created_at')]);if(lr.error)throw lr.error;if(yr.error)throw yr.error;S.lists=lr.data||[];S.layouts=(yr.data||[]).map(x=>({...x,definition:normalizeDefinition(x.definition)}));
 const url=new URL(location.href),ql=url.searchParams.get('list'),qy=url.searchParams.get('layout');S.listId=[ql,localStorage.getItem('yn:list'),S.listId].find(x=>S.lists.some(l=>l.id===x))||S.lists[0]?.id||null;const l=currentList();S.layoutId=[qy,l?.default_layout_id,localStorage.getItem('yn:layout'),S.layoutId].find(x=>S.layouts.some(y=>y.id===x))||S.layouts[0]?.id||null;renderSelectors();
}
function renderSelectors(){const ls=$('requestListSelect'),ys=$('layoutSelect');ls.innerHTML=S.lists.map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join('');ys.innerHTML=S.layouts.map(x=>`<option value="${x.id}">${esc(x.title)}</option>`).join('');if(S.listId)ls.value=S.listId;if(S.layoutId)ys.value=S.layoutId}
async function saveDefaultLayout(layoutId){const l=currentList();if(!l||!layoutId||l.default_layout_id===layoutId)return;const {error}=await db.from('yamim_noraim_request_lists').update({default_layout_id:layoutId,updated_at:new Date().toISOString()}).eq('id',l.id);if(error)throw error;l.default_layout_id=layoutId}
async function load(force=false){
 S.selectedGroup=null;touchSelected=null;$('tools').classList.remove('show');if(!S.listId||!S.layoutId){S.reqs=[];S.assignments=[];S.seats=[];render();return setStatus('יש להגדיר לפחות רשימת בקשות ותצורה אחת.')}
 S.layout=currentLayout();S.seats=engineSeats(S.layout);
 if(S.editSession&&!force){render();setStatus('מצב טיוטה: השינויים עדיין לא נשמרו. אפשר להזיז, לפצל או לשחרר קבוצות ואז לשמור או לחזור למצב הקודם.');return}
 setStatus('טוען...');
 const [rr,ar]=await Promise.all([db.from('yamim_noraim_requests').select('family_id,men,women,updated_at').eq('request_list_id',S.listId),db.from('yamim_noraim_seating_v2').select('id,family_id,section,seat_id,seat_group,created_at,updated_at').eq('request_list_id',S.listId).eq('layout_id',S.layoutId)]);if(rr.error)throw rr.error;if(ar.error)throw ar.error;
 const req=rr.data||[],ids=[...new Set(req.map(x=>x.family_id))];let fam=[];if(ids.length){const f=await db.from('yamim_noraim_families').select('id,family_name,notes').in('id',ids);if(f.error)throw f.error;fam=f.data||[]}const fm=new Map(fam.map(x=>[x.id,x]));S.reqs=req.map(x=>({...x,family_name:fm.get(x.family_id)?.family_name||'',notes:fm.get(x.family_id)?.notes||''})).sort((a,b)=>a.family_name.localeCompare(b.family_name,'he'));S.assignments=(ar.data||[]).map(a=>({...a,family_name:fm.get(a.family_id)?.family_name||'',draft_origin:'original'}));
 const valid=new Set(S.seats.map(s=>s.id));const dangling=S.assignments.filter(a=>!valid.has(a.seat_id)).length;render();setStatus(dangling?`יש ${dangling} שיבוצים ישנים שאינם קיימים בתצורה הנוכחית. ערוך את התצורה או נקה את השיבוץ.`:'השינויים נשמרים אוטומטית.');
}
function draftOrigin(g){return S.editSession?.groupOrigins?.get(String(g))||'manual'}
async function createGroup(familyId,section,seats,g=groupId(),origin=null){if(!seats.length)return g;if(S.editSession){const o=origin||draftOrigin(g);S.editSession.groupOrigins.set(String(g),o);const fam=familyName(familyId),now=new Date().toISOString();S.assignments.push(...seats.map(seat=>({id:'draft:'+uid('seat'),request_list_id:S.listId,layout_id:S.layoutId,family_id:familyId,family_name:fam,section,seat_id:seat.id,seat_group:g,created_at:now,updated_at:now,draft_origin:o})));return g}const rows=seats.map(seat=>({request_list_id:S.listId,layout_id:S.layoutId,family_id:familyId,section,seat_id:seat.id,seat_group:g}));const {error}=await db.from('yamim_noraim_seating_v2').insert(rows);if(error)throw error;return g}
async function deleteGroup(g){if(S.editSession){S.assignments=S.assignments.filter(a=>(a.seat_group||a.id)!==g);return}const {error}=await db.from('yamim_noraim_seating_v2').delete().eq('request_list_id',S.listId).eq('layout_id',S.layoutId).eq('seat_group',g);if(error)throw error}
async function deleteAssignment(id){if(S.editSession){S.assignments=S.assignments.filter(a=>a.id!==id);return}const {error}=await db.from('yamim_noraim_seating_v2').delete().eq('id',id);if(error)throw error}
async function patchGroup(id,g){if(S.editSession){const a=S.assignments.find(x=>x.id===id);if(!a)return;const old=a.seat_group||a.id,o=draftOrigin(old);a.seat_group=g;S.editSession.groupOrigins.set(String(g),o);return}const {error}=await db.from('yamim_noraim_seating_v2').update({seat_group:g,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error}
function segment(target){return S.seats.filter(s=>s.section===target.section&&s.segment===target.segment).sort((a,b)=>a.order-b.order)}
function freeRun(target,ignore=null){const line=segment(target),idx=line.findIndex(s=>s.id===target.id),occ=new Set(S.assignments.filter(a=>(a.seat_group||a.id)!==ignore).map(a=>a.seat_id));if(idx<0||occ.has(target.id))return[];let l=idx,r=idx;while(l>0&&!occ.has(line[l-1].id))l--;while(r<line.length-1&&!occ.has(line[r+1].id))r++;return line.slice(l,r+1)}
function chooseFrom(target,n,ignore=null){const run=freeRun(target,ignore);if(run.length<n)return{chosen:run,available:run.length};const idx=run.findIndex(s=>s.id===target.id),start=Math.min(Math.max(0,idx),run.length-n);return{chosen:run.slice(start,start+n),available:run.length}}
function render(){renderFront();renderRequests('women');renderRequests('men');renderMaps();const nm=S.reqs.reduce((x,r)=>x+(Number(r.men)||0),0),nw=S.reqs.reduce((x,r)=>x+(Number(r.women)||0),0);$('sumFamilies').textContent=S.reqs.filter(r=>(r.men||0)+(r.women||0)>0).length+' משפחות';$('sumMen').textContent=`גברים ${S.assignments.filter(a=>a.section==='men').length}/${nm} · ${S.seats.filter(s=>s.section==='men').length} כיסאות`;$('sumWomen').textContent=`נשים ${S.assignments.filter(a=>a.section==='women').length}/${nw} · ${S.seats.filter(s=>s.section==='women').length} כיסאות`;bindTouch();window.dispatchEvent(new CustomEvent('yn:seating-rendered'))}
function renderFront(){const f=S.layout?.definition?.front||{};$('frontLeft').textContent=f.left||'';$('frontCenter').textContent=f.center||'';$('frontRight').textContent=f.right||''}
function renderRequests(sec){const box=$(sec==='men'?'menRequests':'womenRequests');box.innerHTML=S.reqs.filter(r=>requestCount(r.family_id,sec)>0).map(r=>{const need=requestCount(r.family_id,sec),got=assignedCount(r.family_id,sec),rem=Math.max(0,need-got),fr=getFrags(r.family_id,sec,rem);return `<div class="family"><div class="fname">${esc(r.family_name)}</div><div class="frags">${fr.map((n,i)=>`<div class="fragwrap"><div class="frag" draggable="true" data-family-id="${r.family_id}" data-family="${esc(r.family_name)}" data-section="${sec}" data-index="${i}" data-count="${n}">${Array.from({length:n},()=>'<span class="fseat"></span>').join('')}</div>${n>1?`<button class="splitmini" data-family-id="${r.family_id}" data-section="${sec}" data-index="${i}" data-count="${n}">פצל</button>`:''}</div>`).join('')}</div><div class="progress">שובצו ${got} מתוך ${need}${rem?' · נותרו '+rem:''}</div>${r.notes?`<div class="note">${esc(r.notes)}</div>`:''}</div>`}).join('');box.querySelectorAll('.frag').forEach(el=>el.addEventListener('dragstart',e=>startFragDrag(e,el)));box.querySelectorAll('.splitmini').forEach(b=>b.onclick=()=>openPreSplit(b.dataset.familyId,b.dataset.section,+b.dataset.index,+b.dataset.count))}
function ghost(n){const g=document.createElement('div');g.className='ghost';for(let i=0;i<n;i++)g.appendChild(document.createElement('span'));document.body.appendChild(g);return g}
function startFragDrag(e,el){const d={kind:'request',familyId:el.dataset.familyId,family:el.dataset.family,section:el.dataset.section,index:+el.dataset.index,count:+el.dataset.count};e.dataTransfer.setData('application/json',JSON.stringify(d));const g=ghost(d.count);e.dataTransfer.setDragImage(g,8,16);setTimeout(()=>g.remove(),0)}
function openPreSplit(f,s,index,count){if(count<2)return;const d=$('splitDialog'),c=$('splitChoices');$('splitText').textContent=`פיצול ${familyName(f)}: ${count} מקומות`;c.innerHTML='';for(let n=1;n<count;n++){const b=document.createElement('button');b.className='btn';b.textContent=`${n} + ${count-n}`;b.onclick=()=>{const rem=Math.max(0,requestCount(f,s)-assignedCount(f,s)),a=getFrags(f,s,rem);a.splice(index,1,n,count-n);setFrags(f,s,a);d.close();renderRequests(s);bindTouch()};c.appendChild(b)}d.showModal()}
function seatHtml(s){const a=S.assignments.find(x=>x.seat_id===s.id);let cls='',lab='',g='';if(a){cls=' taken';if(S.editSession&&a.draft_origin==='proposal')cls+=' draftProposal';g=a.seat_group||a.id;const all=S.assignments.filter(x=>(x.seat_group||x.id)===g),ord=rowOrder(s.section,s.row_id,s.area_id).filter(x=>all.some(y=>y.seat_id===x.id)),p=ord.findIndex(x=>x.id===s.id);if(p===Math.floor((ord.length-1)/2))lab=`<span class="gname">${esc(a.family_name)}</span>`;if(g===S.selectedGroup)cls+=' selected'}return `<div class="seat${cls}" data-seat="${s.id}" ${a?`draggable="true" data-group="${esc(g)}"`:''}>${lab}</div>`}
function gridCellHtml(area,r,c,cell){if(cell.type==='seat'){const s=S.seats.find(x=>x.area_id===area.id&&x.row===r+1&&x.col===c+1);return s?seatHtml(s):'<div class="seat unavailable"></div>'}if(cell.type==='stage')return `<div class="stageCell">${esc(cell.label||'במה')}</div>`;return `<div class="${cell.type==='aisle'?'aisleCell':'spacerCell'}"></div>`}
function areaRowHtml(area,r){const row=area.grid.cells[r]||[];return `<div class="row areaRow"><span class="rn">${r+1}</span><div class="rowseats" data-area="${area.id}" data-row="${r+1}">${row.map((cell,c)=>gridCellHtml(area,r,c,cell)).join('')}</div></div>`}
function areaHtml(area){const sex=area.section==='women'?'נשים':'גברים';return `<section class="seatArea" data-area="${area.id}" data-section="${area.section}"><div class="areaTitle"><b>${esc(area.name)}</b><span>${sex}</span></div><div class="areaMap">${Array.from({length:area.grid.rows},(_,r)=>areaRowHtml(area,r)).join('')}</div></section>`}
function levelHtml(level){const buckets={front:[],left:[],center:[],right:[],rear:[]};for(const a of level.areas)(buckets[a.position]||buckets.center).push(a);const slot=(pos,label)=>`<div class="areaSlot position-${pos}" data-position="${pos}">${buckets[pos].length?buckets[pos].map(areaHtml).join(''):`<div class="emptyAreaSlot">${label}</div>`}</div>`;return `<section class="levelSeatMap" data-level="${level.id}"><h3>${esc(level.name)}</h3><div class="areasCanvas">${slot('front','קדמי')}${slot('left','שמאל')}${slot('center','מרכז')}${slot('right','ימין')}${slot('rear','אחורי')}</div></section>`}
function renderMaps(){const map=$('layoutMap'),d=toAreaDefinition(S.layout);map.innerHTML=d.levels.map(levelHtml).join('');document.querySelectorAll('.seat[data-seat]').forEach(el=>{el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',dropSeat);if(el.dataset.group){el.addEventListener('dragstart',e=>startGroupDrag(e,el));el.onclick=()=>selectGroup(el.dataset.group)}})}
async function dropSeat(e){e.preventDefault();let d;try{d=JSON.parse(e.dataTransfer.getData('application/json'))}catch{return}const t=S.seats.find(s=>s.id===e.currentTarget.dataset.seat);if(!t)return;if(d.kind==='request')return placeRequest(d,t);if(d.kind==='group')return placeGroup(d,t)}
async function placeRequest(d,t){if(d.section!==t.section)return alert('יש לשבץ בצד המתאים.');const x=chooseFrom(t,d.count);if(!x.chosen.length)return alert('אין כאן מקום פנוי.');const rem=Math.max(0,requestCount(d.familyId,d.section)-assignedCount(d.familyId,d.section)),a=getFrags(d.familyId,d.section,rem);if(x.chosen.length<d.count){if(!confirm(`יש כאן רק ${x.chosen.length} מקומות רצופים. לפצל ${d.count} ל־${x.chosen.length}+${d.count-x.chosen.length}?`))return;a.splice(d.index,1,d.count-x.chosen.length);await createGroup(d.familyId,d.section,x.chosen);setFrags(d.familyId,d.section,a)}else{a.splice(d.index,1);await createGroup(d.familyId,d.section,x.chosen);setFrags(d.familyId,d.section,a)}await load()}
function startGroupDrag(e,el){const g=el.dataset.group,n=S.assignments.filter(a=>(a.seat_group||a.id)===g).length;e.dataTransfer.setData('application/json',JSON.stringify({kind:'group',group:g,count:n}));const x=ghost(n);e.dataTransfer.setDragImage(x,8,16);setTimeout(()=>x.remove(),0)}
async function placeGroup(d,t){const cur=S.assignments.filter(a=>(a.seat_group||a.id)===d.group);if(!cur.length||cur[0].section!==t.section)return alert('יש להזיז קבוצה בתוך אותו צד.');const x=chooseFrom(t,cur.length,d.group);if(!x.chosen.length)return alert('אין כאן מקום פנוי.');if(x.chosen.length<cur.length){if(!confirm(`יש כאן רק ${x.chosen.length} מקומות רצופים. לפצל את הקבוצה?`))return;return splitAndMove(cur,x.chosen)}const fam=cur[0].family_id,sec=cur[0].section,origin=cur[0].draft_origin||draftOrigin(d.group);await deleteGroup(d.group);await createGroup(fam,sec,x.chosen,d.group,origin);await load()}
async function splitAndMove(cur,chosen){const objs=cur.map(x=>S.seats.find(s=>s.id===x.seat_id)).filter(Boolean),first=objs[0],ord=rowOrder(cur[0].section,first?.row_id,first?.area_id),sorted=[...cur].sort((a,b)=>ord.findIndex(x=>x.id===a.seat_id)-ord.findIndex(x=>x.id===b.seat_id)),moving=sorted.slice(0,chosen.length),ng=groupId(),origin=cur[0].draft_origin||draftOrigin(cur[0].seat_group||cur[0].id);if(S.editSession)S.editSession.groupOrigins.set(String(ng),origin);for(const a of moving)await deleteAssignment(a.id);await createGroup(cur[0].family_id,cur[0].section,chosen,ng,origin);await load()}
function selectGroup(g){S.selectedGroup=g;const a=S.assignments.filter(x=>(x.seat_group||x.id)===g);if(!a.length)return;const proposal=S.editSession&&a.some(x=>x.draft_origin==='proposal');$('groupTitle').textContent=`${a[0].family_name} — ${a.length} מקומות${proposal?' · הצעה':''}`;$('splitCount').innerHTML='';for(let i=1;i<a.length;i++)$('splitCount').insertAdjacentHTML('beforeend',`<option>${i}</option>`);$('splitBtn').style.display=a.length>1?'inline-block':'none';$('releaseGroup').textContent=S.editSession?(proposal?'הסר את ההצעה':'שחרר מהטיוטה'):'שחרר קבוצה';$('tools').classList.add('show');renderMaps();bindTouch()}
async function splitGroup(){const a=S.assignments.filter(x=>(x.seat_group||x.id)===S.selectedGroup),n=+$('splitCount').value;if(a.length<2)return;const objs=a.map(x=>S.seats.find(s=>s.id===x.seat_id)).filter(Boolean),first=objs[0],ord=rowOrder(a[0].section,first?.row_id,first?.area_id);objs.sort((x,y)=>ord.findIndex(z=>z.id===x.id)-ord.findIndex(z=>z.id===y.id));const ids=new Set(objs.slice(n).map(s=>s.id)),ng=groupId(),origin=a[0].draft_origin||draftOrigin(S.selectedGroup);if(S.editSession)S.editSession.groupOrigins.set(String(ng),origin);for(const x of a.filter(q=>ids.has(q.seat_id)))await patchGroup(x.id,ng);await load()}
async function clearCurrent(){if(S.editSession)return alert('יש טיוטת שיבוץ פתוחה. שמור אותה או חזור למצב הקודם לפני איפוס השיבוץ.');if(!confirm(`לאפס את כל השיבוצים ברשימה "${currentList()?.title||''}" ובתצורה "${currentLayout()?.title||''}"?`))return;const {error}=await db.from('yamim_noraim_seating_v2').delete().eq('request_list_id',S.listId).eq('layout_id',S.layoutId);if(error)return alert(error.message);await load()}
function splitProposalRuns(seats){const out=[];let cur=[];for(const seat of [...seats].sort((a,b)=>String(a.area_id).localeCompare(String(b.area_id))||a.row-b.row||a.order-b.order)){const p=cur[cur.length-1];if(!p){cur=[seat];continue}if(seat.segment===p.segment&&seat.order===p.order+1)cur.push(seat);else{out.push(cur);cur=[seat]}}if(cur.length)out.push(cur);return out}
function beginDraft(plan,source='algorithm'){
 if(S.editSession)return{ok:false,issues:['כבר קיימת טיוטת שיבוץ פתוחה.']};const snapshot=clone(S.assignments),occupied=new Set(snapshot.map(a=>a.seat_id)),issues=[],planned=new Map(),runs=[];
 for(const p of plan?.placements||[]){const r=(p.family_id&&S.reqs.find(x=>x.family_id===p.family_id))||S.reqs.find(x=>x.family_name===String(p.family||''));if(!r){issues.push(`המשפחה ${p.family||''} אינה קיימת ברשימה.`);continue}if(!['men','women'].includes(p.section)){issues.push(`${r.family_name}: צד לא תקין.`);continue}const seats=[];for(const id of [...new Set(Array.isArray(p.seat_ids)?p.seat_ids:[])]){const s=S.seats.find(x=>x.id===id);if(!s||s.section!==p.section){issues.push(`${r.family_name}: הכיסא ${id} אינו קיים בצד המתאים.`);continue}if(occupied.has(id)){issues.push(`${r.family_name}: הכיסא ${id} כבר תפוס.`);continue}seats.push(s);occupied.add(id)}const key=r.family_id+'|'+p.section;planned.set(key,(planned.get(key)||0)+seats.length);for(const run of splitProposalRuns(seats))runs.push({familyId:r.family_id,family:r.family_name,section:p.section,seats:run})}
 for(const [key,n] of planned){const [fid,sec]=key.split('|'),remaining=Math.max(0,requestCount(fid,sec)-snapshot.filter(a=>a.family_id===fid&&a.section===sec).length);if(n>remaining)issues.push(`${familyName(fid)}: ההצעה כוללת ${n} מקומות אך נותרו ${remaining}.`)}
 if(issues.length)return{ok:false,issues:[...new Set(issues)]};const groupOrigins=new Map();for(const a of snapshot)groupOrigins.set(String(a.seat_group||a.id),'original');S.editSession={snapshot,source,startedAt:new Date().toISOString(),groupOrigins};for(const r of runs){const g=`proposal:${source}:${groupId()}`;groupOrigins.set(g,'proposal');const now=new Date().toISOString();S.assignments.push(...r.seats.map(s=>({id:'draft:'+uid('seat'),request_list_id:S.listId,layout_id:S.layoutId,family_id:r.familyId,family_name:r.family,section:r.section,seat_id:s.id,seat_group:g,created_at:now,updated_at:now,draft_origin:'proposal'})))}render();setStatus('טיוטת שיבוץ: ההצעה בסגול. אפשר להזיז גם אותה וגם שיבוצים קיימים, להסיר קבוצות, ואז לשמור או לחזור למצב הקודם.');return{ok:true,groups:runs.length,seats:runs.reduce((n,r)=>n+r.seats.length,0)}
}
function cancelDraft(){if(!S.editSession)return false;S.assignments=clone(S.editSession.snapshot);S.editSession=null;S.selectedGroup=null;render();setStatus('הטיוטה בוטלה. חזרת לשיבוץ שהיה לפני ההצעה.');return true}
function validateDraft(){const issues=[],seen=new Set(),counts=new Map(),validSeats=new Set(S.seats.map(s=>s.id));for(const a of S.assignments){if(!validSeats.has(a.seat_id))issues.push(`הכיסא ${a.seat_id} אינו קיים בתצורה.`);if(seen.has(a.seat_id))issues.push(`הכיסא ${a.seat_id} משובץ פעמיים.`);seen.add(a.seat_id);const k=a.family_id+'|'+a.section;counts.set(k,(counts.get(k)||0)+1)}for(const [k,n] of counts){const [fid,sec]=k.split('|'),need=requestCount(fid,sec);if(n>need)issues.push(`${familyName(fid)}: שובצו ${n} מקומות בצד ${sec==='men'?'גברים':'נשים'} אך התבקשו ${need}.`)}return[...new Set(issues)]}
async function commitDraft(){if(!S.editSession)throw Error('אין טיוטה פתוחה.');const issues=validateDraft();if(issues.length)throw Error(issues.slice(0,8).join('\n'));const rows=S.assignments.map(a=>({family_id:a.family_id,section:a.section,seat_id:a.seat_id,seat_group:a.seat_group||null}));const {error}=await db.rpc('replace_yamim_noraim_seating_v2',{p_request_list_id:S.listId,p_layout_id:S.layoutId,p_rows:rows});if(error)throw error;S.editSession=null;await load(true);return rows.length}
function addMobileChrome(){if(!touchMode)return;document.body.classList.add('mobile-view-hall');if(!document.querySelector('.mobileNav')){const n=document.createElement('div');n.className='mobileNav';n.innerHTML='<button data-view="hall" class="active">תרשים</button><button data-view="men">בקשות גברים</button><button data-view="women">בקשות נשים</button>';document.querySelector('.workspace')?.before(n);n.querySelectorAll('button').forEach(b=>b.onclick=()=>{document.body.classList.remove('mobile-view-hall','mobile-view-men','mobile-view-women');document.body.classList.add('mobile-view-'+b.dataset.view);n.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b))})}if(!$('touchBar')){const b=document.createElement('div');b.id='touchBar';b.className='touchBar';b.innerHTML='<div id="touchBarText" class="touchBarText"></div><button id="touchCancel">בטל</button>';document.body.appendChild(b);$('touchCancel').onclick=clearTouch}}
function clearTouch(){touchSelected=null;document.querySelectorAll('.touchSelected,.touchTargetHint').forEach(x=>x.classList.remove('touchSelected','touchTargetHint'));if($('touchBar'))$('touchBar').style.display='none'}
function bindTouch(){if(!touchMode)return;addMobileChrome();document.querySelectorAll('.frag').forEach(el=>{if(el.dataset.tb)return;el.dataset.tb='1';el.onclick=e=>{e.preventDefault();touchSelected={kind:'request',familyId:el.dataset.familyId,family:el.dataset.family,section:el.dataset.section,index:+el.dataset.index,count:+el.dataset.count};showTouch(`${touchSelected.family} — ${touchSelected.count} מקומות. גע בכיסא היעד.`);document.body.classList.remove('mobile-view-men','mobile-view-women');document.body.classList.add('mobile-view-hall')}});document.querySelectorAll('.seat[data-seat]').forEach(el=>{if(el.dataset.tb)return;el.dataset.tb='1';el.addEventListener('click',async e=>{if(!touchSelected){if(el.dataset.group){e.stopImmediatePropagation();touchSelected={kind:'group',group:el.dataset.group};showTouch('בחר כיסא יעד להעברת הקבוצה.')}return}e.preventDefault();e.stopImmediatePropagation();const t=S.seats.find(s=>s.id===el.dataset.seat);try{if(touchSelected.kind==='request')await placeRequest({...touchSelected},t);else await placeGroup({...touchSelected},t)}finally{clearTouch()}},true)})}
function showTouch(t){$('touchBarText').textContent=t;$('touchBar').style.display='flex';document.querySelectorAll('.seat:not(.taken)').forEach(x=>x.classList.add('touchTargetHint'))}
$('requestListSelect').onchange=async e=>{if(S.editSession){e.target.value=S.listId;return alert('יש טיוטת שיבוץ פתוחה. שמור אותה או חזור למצב הקודם לפני מעבר לרשימה אחרת.')}S.listId=e.target.value;localStorage.setItem('yn:list',S.listId);const l=currentList();S.layoutId=(l?.default_layout_id&&S.layouts.some(x=>x.id===l.default_layout_id))?l.default_layout_id:(S.layouts[0]?.id||null);if(S.layoutId)localStorage.setItem('yn:layout',S.layoutId);renderSelectors();await load()};
$('layoutSelect').onchange=async e=>{if(S.editSession){e.target.value=S.layoutId;return alert('יש טיוטת שיבוץ פתוחה. שמור אותה או חזור למצב הקודם לפני החלפת תצורה.')}S.layoutId=e.target.value;localStorage.setItem('yn:layout',S.layoutId);try{await saveDefaultLayout(S.layoutId)}catch(err){alert('התצורה הוחלפה, אך לא ניתן היה לשמור אותה כברירת המחדל: '+err.message)}await load()};
$('clearBtn').onclick=clearCurrent;$('splitBtn').onclick=splitGroup;$('releaseGroup').onclick=async()=>{if(!S.selectedGroup)return;const draft=S.editSession,proposal=draft&&S.assignments.some(x=>(x.seat_group||x.id)===S.selectedGroup&&x.draft_origin==='proposal');if(!confirm(proposal?'להסיר את השיבוץ המוצע מהטיוטה?':'לשחרר את הקבוצה?'))return;await deleteGroup(S.selectedGroup);await load()};$('closeTools').onclick=()=>{S.selectedGroup=null;$('tools').classList.remove('show');renderMaps();bindTouch()};$('closeSplit').onclick=()=>$('splitDialog').close();
window.YN={S,db,$,esc,rowOrder,requestCount,assignedCount,familyName,createGroup,deleteGroup,load,chooseFrom,groupId,setStatus,render,beginDraft,cancelDraft,commitDraft,isDraft:()=>!!S.editSession};
(async()=>{if(await gate())try{await loadMeta();await load();addMobileChrome()}catch(e){setStatus('שגיאה: '+e.message)}})();
})();