(()=>{const BASE='https://fhilbjbuhtqdwvxhiedz.supabase.co/rest/v1/',KEY='sb_publishable_sXoO_u65OB-SPt9OFPiz5A_XMUIIprl',H={'apikey':KEY,'Content-Type':'application/json'};const REG=BASE+'yamim_noraim_registrations',SEAT=BASE+'yamim_noraim_seating',SET=BASE+'yamim_noraim_seating_settings';const layouts={1:{men:[4,3,4],women:[5,5],desc:'תצורה 1 — גברים מימין 4 | 3 | 4, נשים משמאל 5 | 5. המעברים ברוחב כיסא; בשורה 8 המעברים מוחלפים בכיסאות. הבמה בגברים בשורות 3–4.'},2:{men:[4,3,3],women:[6,5],desc:'תצורה 2 — הטור הרחב מימין בשני הצדדים: גברים 4 | 3 | 3, נשים 6 | 5. הבמה בגברים בשורות 3–4.'}};const S={event:'rh',layoutNo:1,row0Men:false,row0Women:false,regs:[],assignments:[],seats:[],selectedGroup:null};const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),gid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();const reqKey=sec=>S.event==='rh'?(sec==='men'?'rh_men':'rh_women'):(sec==='men'?'yk_men':'yk_women'),prefix=()=>`L${S.layoutNo}-`;
function buildSeats(){const c=layouts[S.layoutNo],o=[];if(S.row0Men)for(let i=1;i<=2;i++)o.push({id:`L${S.layoutNo}-M-0-B0-${i}`,section:'men',row:0,block:0,order:i,rowzero:true,segment:'M-0-B0'});if(S.row0Women)for(let i=1;i<=2;i++)o.push({id:`L${S.layoutNo}-W-0-B1-${i}`,section:'women',row:0,block:1,order:i,rowzero:true,segment:'W-0-B1'});for(let r=1;r<=8;r++){c.men.forEach((n,b)=>{if((r===3||r===4)&&b===1)return;for(let i=1;i<=n;i++)o.push({id:`L${S.layoutNo}-M-${r}-B${b}-${i}`,section:'men',row:r,block:b,order:i,segment:r===8?'M-8-all':`M-${r}-B${b}`})});if(r===8)o.push({id:`L${S.layoutNo}-M-8-X0`,section:'men',row:r,block:'x0',order:1,extra:true,segment:'M-8-all'},{id:`L${S.layoutNo}-M-8-X1`,section:'men',row:r,block:'x1',order:1,extra:true,segment:'M-8-all'});c.women.forEach((n,b)=>{for(let i=1;i<=n;i++)o.push({id:`L${S.layoutNo}-W-${r}-B${b}-${i}`,section:'women',row:r,block:b,order:i,segment:r===8?'W-8-all':`W-${r}-B${b}`})});if(r===8)o.push({id:`L${S.layoutNo}-W-8-X0`,section:'women',row:r,block:'x0',order:1,extra:true,segment:'W-8-all'})}return o}
function rowOrder(sec,row){const c=layouts[S.layoutNo],a=[];if(sec==='men'){for(let b=0;b<c.men.length;b++){a.push(...S.seats.filter(s=>s.section===sec&&s.row===row&&s.block===b).sort((x,y)=>x.order-y.order));if(row===8&&b<2){const x=S.seats.find(s=>s.id===`L${S.layoutNo}-M-8-X${b}`);if(x)a.push(x)}}}else{for(let b=0;b<c.women.length;b++){a.push(...S.seats.filter(s=>s.section===sec&&s.row===row&&s.block===b).sort((x,y)=>x.order-y.order));if(row===8&&b===0){const x=S.seats.find(s=>s.id===`L${S.layoutNo}-W-8-X0`);if(x)a.push(x)}}}return a}
const assignedCount=(f,s)=>S.assignments.filter(a=>a.family_name===f&&a.section===s).length,fragKey=(f,s)=>`yn-frag:${S.event}:${S.layoutNo}:${s}:${f}`;
function getFrags(f,s,remaining){if(remaining<=0)return[];try{const a=JSON.parse(localStorage.getItem(fragKey(f,s))||'[]');if(Array.isArray(a)&&a.every(n=>Number.isInteger(n)&&n>0)&&a.reduce((x,y)=>x+y,0)===remaining)return a}catch{}return[remaining]}
const setFrags=(f,s,a)=>localStorage.setItem(fragKey(f,s),JSON.stringify(a));
async function load(){S.selectedGroup=null;$('tools')?.classList.remove('show');$('status').textContent='טוען...';try{const [rr,sr,st]=await Promise.all([fetch(REG+'?select=family_name,rh_men,rh_women,yk_men,yk_women,notes&order=family_name.asc',{headers:H}),fetch(SEAT+'?select=id,event,section,seat_id,family_name,seat_group&event=eq.'+S.event,{headers:H}),fetch(SET+'?select=row0_men,row0_women&event=eq.'+S.event+'&layout_no=eq.'+S.layoutNo,{headers:H})]);if(!rr.ok||!sr.ok||!st.ok)throw Error('שגיאה בקריאת הנתונים');S.regs=await rr.json();const set=await st.json();S.row0Men=!!set[0]?.row0_men;S.row0Women=!!set[0]?.row0_women;S.seats=buildSeats();S.assignments=(await sr.json()).filter(a=>a.seat_id.startsWith(prefix()));YN.render();$('status').textContent='השינויים נשמרים אוטומטית.'}catch(e){$('status').textContent='שגיאה: '+e.message}}
function segment(target){return target.row===8?rowOrder(target.section,target.row):rowOrder(target.section,target.row).filter(s=>s.segment===target.segment)}
function freeRun(target,ignore=null){const line=segment(target),idx=line.findIndex(s=>s.id===target.id),occ=new Set(S.assignments.filter(a=>(a.seat_group||a.id)!==ignore).map(a=>a.seat_id));if(idx<0||occ.has(target.id))return[];let l=idx,r=idx;while(l>0&&!occ.has(line[l-1].id))l--;while(r<line.length-1&&!occ.has(line[r+1].id))r++;return line.slice(l,r+1)}
function chooseFrom(target,n,ignore=null){const run=freeRun(target,ignore);if(run.length<n)return{chosen:run,available:run.length};const idx=run.findIndex(s=>s.id===target.id),start=Math.min(Math.max(0,idx),run.length-n);return{chosen:run.slice(start,start+n),available:run.length}}
async function createGroup(f,s,list,g=gid()){for(const seat of list){const r=await fetch(SEAT,{method:'POST',headers:{...H,'Prefer':'return=minimal'},body:JSON.stringify({event:S.event,section:s,seat_id:seat.id,family_name:f,seat_group:g})});if(!r.ok)throw Error(await r.text())}return g}
async function deleteGroup(g){return fetch(SEAT+'?seat_group=eq.'+encodeURIComponent(g),{method:'DELETE',headers:H})}
async function patchGroup(id,g){return fetch(SEAT+'?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:{...H,'Prefer':'return=minimal'},body:JSON.stringify({seat_group:g})})}
async function saveSettings(){const body={event:S.event,layout_no:S.layoutNo,row0_men:S.row0Men,row0_women:S.row0Women,updated_at:new Date().toISOString()};return fetch(SET+'?on_conflict=event,layout_no',{method:'POST',headers:{...H,'Prefer':'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(body)})}
async function toggleRow0(sec){const isM=sec==='men',next=!(isM?S.row0Men:S.row0Women),code=isM?'M':'W';if(!next&&S.assignments.some(a=>a.seat_id.startsWith(`L${S.layoutNo}-${code}-0-`))&&!confirm('כיבוי שורה 0 ישחרר את השיבוצים שעליה. להמשיך?'))return;if(!next)await fetch(SEAT+'?event=eq.'+S.event+'&seat_id=like.'+encodeURIComponent(`L${S.layoutNo}-${code}-0-*`),{method:'DELETE',headers:H});if(isM)S.row0Men=next;else S.row0Women=next;await saveSettings();load()}
async function clearLayout(){if(!confirm('לאפס את כל השיבוצים בחג ובתצורה הנוכחיים?'))return;await fetch(SEAT+'?event=eq.'+S.event+'&seat_id=like.'+encodeURIComponent(prefix()+'*'),{method:'DELETE',headers:H});load()}
window.YN={S,$,esc,gid,layouts,reqKey,prefix,rowOrder,assignedCount,getFrags,setFrags,load,chooseFrom,createGroup,deleteGroup,patchGroup,toggleRow0,clearLayout,H,SEAT};})();