(()=>{
const db=YNGeneric.makeClient(),raw=YNGeneric.makeRawClient(),$=s=>document.querySelector(s),esc=YNGeneric.esc;
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jerusalem',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const dateText=s=>s?new Intl.DateTimeFormat('he-IL',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(s+'T12:00:00Z')):'';
const nextShabbat=()=>{const d=new Date(today()+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+(6-d.getUTCDay()+7)%7);return d.toISOString().slice(0,10)};
const fields={members:[['full_name','שם מלא','text',true],['family_name','שם משפחה','text'],['phone','טלפון','tel'],['email','דוא״ל','email'],['role','ייחוס','select',['ישראל','כהן','לוי']],['status','מצב','select',['פעיל','לא פעיל']],['notes','הערות','textarea']],prayers:[['service_date','תאריך','date',true],['title','תפילה','text',true],['service_time','שעה','time'],['notes','הערות','textarea']],assignments:[['service_date','תאריך','date',true],['duty','תפקיד או עלייה','text',true],['member_id','מתפלל','member'],['person_name','שם אחר / אורח','text'],['notes','הערות','textarea']],events:[['event_date','תאריך','date',true],['title','שם האירוע / שם הנפטר','text',true],['kind','סוג','select',['אירוע','יארצייט','קידוש','שיעור']],['notes','הערות','textarea']],finances:[['entry_date','תאריך','date',true],['description','תיאור','text',true],['member_id','מתפלל','member'],['amount','סכום בש״ח (חיובי לתרומה או התחייבות)','number',true],['status','מצב','select',['פתוח','שולם']],['notes','הערות','textarea']]};
const tables={members:'synagogue_members',prayers:'synagogue_prayers',assignments:'synagogue_assignments',events:'synagogue_events',finances:'synagogue_finances'};
const names={home:'השבת הקרובה',members:'מתפללים ומשפחות',prayers:'תפילות וזמנים',assignments:'גבאות ותפקידים',events:'אירועים ואזכרות',finances:'כספים והתחייבויות'};
let view='home',access,records={},editing=null,filter='';
function message(s){$('#notice').textContent=s; if(s)setTimeout(()=>{if($('#notice').textContent===s)$('#notice').textContent=''},6000)}
function nameFor(id){return records.members?.find(m=>m.id===id)?.full_name||''}
function formatRow(type,x){const title=type==='members'?x.full_name:type==='assignments'?x.duty:type==='finances'?x.description:x.title;
const detail=type==='members'?[x.role,x.phone,x.status].filter(Boolean).join(' · '):type==='prayers'?[dateText(x.service_date),x.service_time?.slice(0,5)].filter(Boolean).join(' · '):type==='assignments'?[dateText(x.service_date),nameFor(x.member_id)||x.person_name].filter(Boolean).join(' · '):type==='events'?[dateText(x.event_date),x.kind].filter(Boolean).join(' · '):[dateText(x.entry_date),nameFor(x.member_id),x.status].filter(Boolean).join(' · ');
return `<div class="row"><strong>${esc(title)}</strong><span>${esc(detail)}</span><span>${type==='finances'?`₪${Number(x.amount).toLocaleString('he-IL')}`:''}</span><button data-edit="${esc(x.id)}" aria-label="עריכת ${esc(title)}">עריכה</button>${x.notes?`<div class="note">${esc(x.notes)}</div>`:''}</div>`}
function list(){const items=(records[view]||[]).filter(x=>!filter||JSON.stringify(x).toLocaleLowerCase('he-IL').includes(filter));$('#view').innerHTML=`<div class="list"><div class="list-head"><h2>${names[view]} <span class="badge">${items.length}</span></h2><input id="search" aria-label="חיפוש ברשימה" placeholder="חיפוש ברשימה" value="${esc(filter)}"></div>${items.length?items.map(x=>formatRow(view,x)).join(''):'<p class="empty" style="padding:20px">אין רשומות להצגה. אפשר להוסיף אחת באמצעות הכפתור למעלה.</p>'}</div>`;$('#search').oninput=e=>{filter=e.target.value;const start=e.target.selectionStart;list();$('#search').focus();$('#search').setSelectionRange(start,start)};$('#view').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(records[view].find(x=>x.id===b.dataset.edit)))}
function home(){const shabbat=nextShabbat(),end=new Date(shabbat+'T12:00:00Z');end.setUTCDate(end.getUTCDate()+1);const endDate=end.toISOString().slice(0,10);const ps=(records.prayers||[]).filter(x=>x.service_date>=today()&&x.service_date<=endDate),as=(records.assignments||[]).filter(x=>x.service_date>=today()&&x.service_date<=endDate),ev=(records.events||[]).filter(x=>x.event_date>=today()&&x.event_date<=endDate);$('#subtitle').textContent=`${dateText(shabbat)} · זמני התפילות מוזנים ידנית`;$('#view').innerHTML=`<div class="overview"><div class="metric"><span>מתפללים במאגר</span><strong>${records.members?.length||0}</strong></div><div class="metric"><span>תפילות עד מוצאי שבת</span><strong>${ps.length}</strong></div><div class="metric"><span>תפקידים משובצים</span><strong>${as.length}</strong></div></div><div class="grid"><section class="panel"><h2>תפילות</h2>${ps.length?ps.map(x=>`<div class="item"><div><strong>${esc(x.title)}</strong><small>${dateText(x.service_date)}</small></div><span class="date-pill">${esc(x.service_time?.slice(0,5)||'—')}</span></div>`).join(''):'<div class="empty">לא הוזנו תפילות לשבת הקרובה.</div>'}</section><section class="panel"><h2>תפקידים ועליות</h2>${as.length?as.map(x=>`<div class="item"><div><strong>${esc(x.duty)}</strong><small>${dateText(x.service_date)}</small></div><span>${esc(nameFor(x.member_id)||x.person_name||'טרם שובץ')}</span></div>`).join(''):'<div class="empty">אין תפקידים משובצים לשבת הקרובה.</div>'}</section><section class="panel"><h2>אירועים ואזכרות</h2>${ev.length?ev.map(x=>`<div class="item"><div><strong>${esc(x.title)}</strong><small>${esc(x.kind)}</small></div><span>${dateText(x.event_date)}</span></div>`).join(''):'<div class="empty">לא נרשמו אירועים לתקופה זו.</div>'}</section><section class="panel"><h2>סידור המקומות</h2><p>ניהול הבקשות, תצורות האולם ושיבוץ המשפחות נשארים זמינים במערכת הקיימת.</p><div class="quick"><button data-link="seating.html">פתיחת מפת הושבה</button><button data-link="admin.html">ניהול בקשות</button></div></section></div><div class="quick"><button data-go="prayers">הוספת תפילה</button><button data-go="assignments">שיבוץ תפקיד</button><button data-go="events">הוספת אירוע</button></div>`;$('#view').querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{setView(b.dataset.go);openEditor()});$('#view').querySelectorAll('[data-link]').forEach(b=>b.onclick=()=>location.href=link(b.dataset.link))}
function link(path){const org=access?.current?.slug;return path+(org?'?org='+encodeURIComponent(org):'')}
function setView(v){view=v;filter='';$('#title').textContent=names[v];$('#eyebrow').textContent=v==='home'?'לוח עבודה':'ניהול הקהילה';$('#subtitle').textContent=v==='home'?'':'הרשומות נשמרות לבית הכנסת הנבחר בלבד';$('#add').hidden=v==='home';$('#add').textContent='הוספת '+({members:'מתפלל',prayers:'תפילה',assignments:'תפקיד',events:'אירוע',finances:'רשומה'}[v]||'רשומה');document.querySelectorAll('#sections button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));v==='home'?home():list()}
function openEditor(item=null){editing=item;$('#dialogTitle').textContent=item?'עריכת רשומה':'הוספת רשומה';$('#delete').hidden=!item;$('#fields').innerHTML=fields[view].map(([key,label,type,required])=>{const val=item?.[key]??(type==='date'?today():type==='select'?required[0]:'');const attrs=`name="${key}" id="field-${key}" ${required===true?'required':''}`;let control;if(type==='select')control=`<select ${attrs}>${required.map(o=>`<option value="${esc(o)}" ${o===val?'selected':''}>${esc(o)}</option>`).join('')}</select>`;else if(type==='member')control=`<select ${attrs}><option value="">— ללא שיוך —</option>${(records.members||[]).map(m=>`<option value="${m.id}" ${m.id===val?'selected':''}>${esc(m.full_name)}</option>`).join('')}</select>`;else if(type==='textarea')control=`<textarea ${attrs}>${esc(val)}</textarea>`;else control=`<input ${attrs} type="${type}" value="${esc(type==='time'?String(val).slice(0,5):val)}" ${type==='number'?'step="0.01" min="0"':''}>`;return `<label class="${type==='textarea'?'wide':''}" for="field-${key}">${label}${control}</label>`}).join('');$('#editor').showModal()}
async function load(){const results=await Promise.all(Object.entries(tables).map(async([key,table])=>{const {data,error}=await db.from(table).select('*').order(key==='members'?'full_name':key==='finances'?'entry_date':key==='events'?'event_date':'service_date',{ascending:key==='members'});if(error)throw error;return [key,data||[]]}));records=Object.fromEntries(results);setView(view)}
async function init(){try{const {data:{session}}=await db.auth.getSession();if(!session){$('#gateMessage').textContent='יש להתחבר כדי לנהל את בית הכנסת.';$('#login').hidden=false;return}access=await YNGeneric.loadAccess(db,session);if(!access.isAdmin||!access.synagogueId){$('#gateMessage').textContent='לחשבון הזה אין הרשאת ניהול של בית כנסת.';return}$('#orgName').textContent=access.current?.name||'בית הכנסת';document.querySelectorAll('[data-href]').forEach(a=>a.href=link(a.dataset.href));$('#gate').hidden=true;$('#app').hidden=false;$('#logout').hidden=false;await load()}catch(e){console.error(e);$('#gateMessage').textContent='לא ניתן לטעון את הנתונים כעת. נסו לרענן את הדף.';message(e.message)}}
$('#login').onclick=async()=>{const {error}=await raw.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.href}});if(error)message(error.message)};$('#logout').onclick=async()=>{await raw.auth.signOut();location.reload()};$('#sections').onclick=e=>{const b=e.target.closest('[data-view]');if(b)setView(b.dataset.view)};$('#add').onclick=()=>openEditor();$('#close').onclick=$('#cancel').onclick=()=>$('#editor').close();$('#editForm').onsubmit=async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.target));for(const k of ['member_id','service_time'])if(k in values&&!values[k])values[k]=null;if(view==='finances')values.amount=Number(values.amount);$('#save').disabled=true;try{const table=tables[view],res=editing?await db.from(table).update(values).eq('id',editing.id).select('id'):await db.from(table).insert(values).select('id');if(res.error)throw res.error;if(!res.data?.length)throw Error('לא נשמרו שינויים. בדקו את הרשאות הניהול.');$('#editor').close();await load();message('הרשומה נשמרה')}catch(err){message('שמירה נכשלה: '+err.message)}finally{$('#save').disabled=false}};$('#delete').onclick=async()=>{if(!editing||!confirm('למחוק את הרשומה?'))return;try{const {error,data}=await db.from(tables[view]).delete().eq('id',editing.id).select('id');if(error)throw error;if(!data?.length)throw Error('לא נמצאה הרשאה למחיקה');$('#editor').close();await load();message('הרשומה נמחקה')}catch(e){message('מחיקה נכשלה: '+e.message)}};init();
})();
